// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/product.proto

package com.test.grpc.product;

public interface CreateProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.CreateProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float pricePerUnit = 1;</code>
   */
  float getPricePerUnit();

  /**
   * <code>string name = 2;</code>
   */
  String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.google.protobuf.StringValue pid = 3;</code>
   */
  boolean hasPid();
  /**
   * <code>.google.protobuf.StringValue pid = 3;</code>
   */
  com.google.protobuf.StringValue getPid();
  /**
   * <code>.google.protobuf.StringValue pid = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getPidOrBuilder();
}
