// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/product.proto

package com.test.grpc.product;

public final class Product {
  private Product() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_StringsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_StringsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductSearchFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductSearchFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_ProductsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_ProductsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_product_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_product_CreateProductRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025product/product.proto\022\007product\032\033google" +
      "/protobuf/empty.proto\032\036google/protobuf/w" +
      "rappers.proto\"!\n\016StringsRequest\022\017\n\007reque" +
      "st\030\001 \003(\t\"B\n\017ProductResponse\022\013\n\003pid\030\001 \001(\t" +
      "\022\024\n\014pricePerUnit\030\002 \001(\002\022\014\n\004name\030\003 \001(\t\"t\n\023" +
      "ProductSearchFilter\0221\n\014pricePerUnit\030\002 \001(" +
      "\0132\033.google.protobuf.FloatValue\022*\n\004name\030\003" +
      " \001(\0132\034.google.protobuf.StringValue\"\202\001\n\024P" +
      "roductUpdateRequest\022\013\n\003pid\030\001 \001(\t\0221\n\014pric" +
      "ePerUnit\030\002 \001(\0132\033.google.protobuf.FloatVa",
      "lue\022*\n\004name\030\003 \001(\0132\034.google.protobuf.Stri" +
      "ngValue\">\n\020ProductsResponse\022*\n\010products\030" +
      "\001 \003(\0132\030.product.ProductResponse\"e\n\024Creat" +
      "eProductRequest\022\024\n\014pricePerUnit\030\001 \001(\002\022\014\n" +
      "\004name\030\002 \001(\t\022)\n\003pid\030\003 \001(\0132\034.google.protob" +
      "uf.StringValue2\302\003\n\016ProductService\022H\n\rCre" +
      "ateProduct\022\035.product.CreateProductReques" +
      "t\032\030.product.ProductResponse\022E\n\rDeletePro" +
      "duct\022\034.google.protobuf.StringValue\032\026.goo" +
      "gle.protobuf.Empty\022I\n\017GetProductByPid\022\034.",
      "google.protobuf.StringValue\032\030.product.Pr" +
      "oductResponse\022G\n\021GetProductsByPids\022\027.pro" +
      "duct.StringsRequest\032\031.product.ProductsRe" +
      "sponse\022A\n\006Search\022\034.product.ProductSearch" +
      "Filter\032\031.product.ProductsResponse\022H\n\rUpd" +
      "ateProduct\022\035.product.ProductUpdateReques" +
      "t\032\030.product.ProductResponseB\031\n\025com.test." +
      "grpc.productP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_product_StringsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_product_StringsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_StringsRequest_descriptor,
        new String[] { "Request", });
    internal_static_product_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_product_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductResponse_descriptor,
        new String[] { "Pid", "PricePerUnit", "Name", });
    internal_static_product_ProductSearchFilter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_product_ProductSearchFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductSearchFilter_descriptor,
        new String[] { "PricePerUnit", "Name", });
    internal_static_product_ProductUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_product_ProductUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductUpdateRequest_descriptor,
        new String[] { "Pid", "PricePerUnit", "Name", });
    internal_static_product_ProductsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_product_ProductsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_ProductsResponse_descriptor,
        new String[] { "Products", });
    internal_static_product_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_product_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_product_CreateProductRequest_descriptor,
        new String[] { "PricePerUnit", "Name", "Pid", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
