// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product/product.proto

package com.test.grpc.product;

public interface ProductSearchFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.ProductSearchFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.FloatValue pricePerUnit = 2;</code>
   */
  boolean hasPricePerUnit();
  /**
   * <code>.google.protobuf.FloatValue pricePerUnit = 2;</code>
   */
  com.google.protobuf.FloatValue getPricePerUnit();
  /**
   * <code>.google.protobuf.FloatValue pricePerUnit = 2;</code>
   */
  com.google.protobuf.FloatValueOrBuilder getPricePerUnitOrBuilder();

  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();
}
