// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

public interface CreateOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.CreateOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  java.util.List<com.test.grpc.order.Product> 
      getProductsList();
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  com.test.grpc.order.Product getProducts(int index);
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  java.util.List<? extends com.test.grpc.order.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  com.test.grpc.order.ProductOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>string userPid = 2;</code>
   */
  java.lang.String getUserPid();
  /**
   * <code>string userPid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserPidBytes();

  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  boolean hasDateCreated();
  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  com.google.protobuf.StringValue getDateCreated();
  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDateCreatedOrBuilder();

  /**
   * <code>.order.OrderStatus status = 4;</code>
   */
  int getStatusValue();
  /**
   * <code>.order.OrderStatus status = 4;</code>
   */
  com.test.grpc.order.OrderStatus getStatus();

  /**
   * <code>float pricePerUnit = 6;</code>
   */
  float getPricePerUnit();

  /**
   * <code>int32 quantity = 7;</code>
   */
  int getQuantity();

  /**
   * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
   */
  boolean hasDateDelivered();
  /**
   * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
   */
  com.google.protobuf.StringValue getDateDelivered();
  /**
   * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDateDeliveredOrBuilder();
}
