// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

/**
 * Protobuf type {@code order.CreateOrderRequest}
 */
public  final class CreateOrderRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:order.CreateOrderRequest)
    CreateOrderRequestOrBuilder {
  // Use CreateOrderRequest.newBuilder() to construct.
  private CreateOrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateOrderRequest() {
    products_ = java.util.Collections.emptyList();
    userPid_ = "";
    status_ = 0;
    pricePerUnit_ = 0F;
    quantity_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CreateOrderRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              products_ = new java.util.ArrayList<com.test.grpc.order.Product>();
              mutable_bitField0_ |= 0x00000001;
            }
            products_.add(
                input.readMessage(com.test.grpc.order.Product.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            userPid_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (dateCreated_ != null) {
              subBuilder = dateCreated_.toBuilder();
            }
            dateCreated_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateCreated_);
              dateCreated_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 53: {

            pricePerUnit_ = input.readFloat();
            break;
          }
          case 56: {

            quantity_ = input.readInt32();
            break;
          }
          case 66: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (dateDelivered_ != null) {
              subBuilder = dateDelivered_.toBuilder();
            }
            dateDelivered_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateDelivered_);
              dateDelivered_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        products_ = java.util.Collections.unmodifiableList(products_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.grpc.order.Order.internal_static_order_CreateOrderRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.grpc.order.Order.internal_static_order_CreateOrderRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.grpc.order.CreateOrderRequest.class, com.test.grpc.order.CreateOrderRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PRODUCTS_FIELD_NUMBER = 1;
  private java.util.List<com.test.grpc.order.Product> products_;
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  public java.util.List<com.test.grpc.order.Product> getProductsList() {
    return products_;
  }
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  public java.util.List<? extends com.test.grpc.order.ProductOrBuilder> 
      getProductsOrBuilderList() {
    return products_;
  }
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  public int getProductsCount() {
    return products_.size();
  }
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  public com.test.grpc.order.Product getProducts(int index) {
    return products_.get(index);
  }
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  public com.test.grpc.order.ProductOrBuilder getProductsOrBuilder(
      int index) {
    return products_.get(index);
  }

  public static final int USERPID_FIELD_NUMBER = 2;
  private volatile java.lang.Object userPid_;
  /**
   * <code>string userPid = 2;</code>
   */
  public java.lang.String getUserPid() {
    java.lang.Object ref = userPid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userPid_ = s;
      return s;
    }
  }
  /**
   * <code>string userPid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUserPidBytes() {
    java.lang.Object ref = userPid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userPid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATECREATED_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue dateCreated_;
  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  public boolean hasDateCreated() {
    return dateCreated_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  public com.google.protobuf.StringValue getDateCreated() {
    return dateCreated_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : dateCreated_;
  }
  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getDateCreatedOrBuilder() {
    return getDateCreated();
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <code>.order.OrderStatus status = 4;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.order.OrderStatus status = 4;</code>
   */
  public com.test.grpc.order.OrderStatus getStatus() {
    com.test.grpc.order.OrderStatus result = com.test.grpc.order.OrderStatus.valueOf(status_);
    return result == null ? com.test.grpc.order.OrderStatus.UNRECOGNIZED : result;
  }

  public static final int PRICEPERUNIT_FIELD_NUMBER = 6;
  private float pricePerUnit_;
  /**
   * <code>float pricePerUnit = 6;</code>
   */
  public float getPricePerUnit() {
    return pricePerUnit_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 7;
  private int quantity_;
  /**
   * <code>int32 quantity = 7;</code>
   */
  public int getQuantity() {
    return quantity_;
  }

  public static final int DATEDELIVERED_FIELD_NUMBER = 8;
  private com.google.protobuf.StringValue dateDelivered_;
  /**
   * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
   */
  public boolean hasDateDelivered() {
    return dateDelivered_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
   */
  public com.google.protobuf.StringValue getDateDelivered() {
    return dateDelivered_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : dateDelivered_;
  }
  /**
   * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getDateDeliveredOrBuilder() {
    return getDateDelivered();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < products_.size(); i++) {
      output.writeMessage(1, products_.get(i));
    }
    if (!getUserPidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userPid_);
    }
    if (dateCreated_ != null) {
      output.writeMessage(3, getDateCreated());
    }
    if (status_ != com.test.grpc.order.OrderStatus.CREATED.getNumber()) {
      output.writeEnum(4, status_);
    }
    if (pricePerUnit_ != 0F) {
      output.writeFloat(6, pricePerUnit_);
    }
    if (quantity_ != 0) {
      output.writeInt32(7, quantity_);
    }
    if (dateDelivered_ != null) {
      output.writeMessage(8, getDateDelivered());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < products_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, products_.get(i));
    }
    if (!getUserPidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userPid_);
    }
    if (dateCreated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDateCreated());
    }
    if (status_ != com.test.grpc.order.OrderStatus.CREATED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (pricePerUnit_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, pricePerUnit_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, quantity_);
    }
    if (dateDelivered_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getDateDelivered());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.grpc.order.CreateOrderRequest)) {
      return super.equals(obj);
    }
    com.test.grpc.order.CreateOrderRequest other = (com.test.grpc.order.CreateOrderRequest) obj;

    boolean result = true;
    result = result && getProductsList()
        .equals(other.getProductsList());
    result = result && getUserPid()
        .equals(other.getUserPid());
    result = result && (hasDateCreated() == other.hasDateCreated());
    if (hasDateCreated()) {
      result = result && getDateCreated()
          .equals(other.getDateCreated());
    }
    result = result && status_ == other.status_;
    result = result && (
        java.lang.Float.floatToIntBits(getPricePerUnit())
        == java.lang.Float.floatToIntBits(
            other.getPricePerUnit()));
    result = result && (getQuantity()
        == other.getQuantity());
    result = result && (hasDateDelivered() == other.hasDateDelivered());
    if (hasDateDelivered()) {
      result = result && getDateDelivered()
          .equals(other.getDateDelivered());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductsCount() > 0) {
      hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getProductsList().hashCode();
    }
    hash = (37 * hash) + USERPID_FIELD_NUMBER;
    hash = (53 * hash) + getUserPid().hashCode();
    if (hasDateCreated()) {
      hash = (37 * hash) + DATECREATED_FIELD_NUMBER;
      hash = (53 * hash) + getDateCreated().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + PRICEPERUNIT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPricePerUnit());
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    if (hasDateDelivered()) {
      hash = (37 * hash) + DATEDELIVERED_FIELD_NUMBER;
      hash = (53 * hash) + getDateDelivered().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.CreateOrderRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.CreateOrderRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.CreateOrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.grpc.order.CreateOrderRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code order.CreateOrderRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:order.CreateOrderRequest)
      com.test.grpc.order.CreateOrderRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.grpc.order.Order.internal_static_order_CreateOrderRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.grpc.order.Order.internal_static_order_CreateOrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.grpc.order.CreateOrderRequest.class, com.test.grpc.order.CreateOrderRequest.Builder.class);
    }

    // Construct using com.test.grpc.order.CreateOrderRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProductsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        productsBuilder_.clear();
      }
      userPid_ = "";

      if (dateCreatedBuilder_ == null) {
        dateCreated_ = null;
      } else {
        dateCreated_ = null;
        dateCreatedBuilder_ = null;
      }
      status_ = 0;

      pricePerUnit_ = 0F;

      quantity_ = 0;

      if (dateDeliveredBuilder_ == null) {
        dateDelivered_ = null;
      } else {
        dateDelivered_ = null;
        dateDeliveredBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.grpc.order.Order.internal_static_order_CreateOrderRequest_descriptor;
    }

    public com.test.grpc.order.CreateOrderRequest getDefaultInstanceForType() {
      return com.test.grpc.order.CreateOrderRequest.getDefaultInstance();
    }

    public com.test.grpc.order.CreateOrderRequest build() {
      com.test.grpc.order.CreateOrderRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.grpc.order.CreateOrderRequest buildPartial() {
      com.test.grpc.order.CreateOrderRequest result = new com.test.grpc.order.CreateOrderRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (productsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          products_ = java.util.Collections.unmodifiableList(products_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.products_ = products_;
      } else {
        result.products_ = productsBuilder_.build();
      }
      result.userPid_ = userPid_;
      if (dateCreatedBuilder_ == null) {
        result.dateCreated_ = dateCreated_;
      } else {
        result.dateCreated_ = dateCreatedBuilder_.build();
      }
      result.status_ = status_;
      result.pricePerUnit_ = pricePerUnit_;
      result.quantity_ = quantity_;
      if (dateDeliveredBuilder_ == null) {
        result.dateDelivered_ = dateDelivered_;
      } else {
        result.dateDelivered_ = dateDeliveredBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.grpc.order.CreateOrderRequest) {
        return mergeFrom((com.test.grpc.order.CreateOrderRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.grpc.order.CreateOrderRequest other) {
      if (other == com.test.grpc.order.CreateOrderRequest.getDefaultInstance()) return this;
      if (productsBuilder_ == null) {
        if (!other.products_.isEmpty()) {
          if (products_.isEmpty()) {
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProductsIsMutable();
            products_.addAll(other.products_);
          }
          onChanged();
        }
      } else {
        if (!other.products_.isEmpty()) {
          if (productsBuilder_.isEmpty()) {
            productsBuilder_.dispose();
            productsBuilder_ = null;
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000001);
            productsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProductsFieldBuilder() : null;
          } else {
            productsBuilder_.addAllMessages(other.products_);
          }
        }
      }
      if (!other.getUserPid().isEmpty()) {
        userPid_ = other.userPid_;
        onChanged();
      }
      if (other.hasDateCreated()) {
        mergeDateCreated(other.getDateCreated());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getPricePerUnit() != 0F) {
        setPricePerUnit(other.getPricePerUnit());
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (other.hasDateDelivered()) {
        mergeDateDelivered(other.getDateDelivered());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.grpc.order.CreateOrderRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.grpc.order.CreateOrderRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.test.grpc.order.Product> products_ =
      java.util.Collections.emptyList();
    private void ensureProductsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        products_ = new java.util.ArrayList<com.test.grpc.order.Product>(products_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.grpc.order.Product, com.test.grpc.order.Product.Builder, com.test.grpc.order.ProductOrBuilder> productsBuilder_;

    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public java.util.List<com.test.grpc.order.Product> getProductsList() {
      if (productsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(products_);
      } else {
        return productsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public int getProductsCount() {
      if (productsBuilder_ == null) {
        return products_.size();
      } else {
        return productsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public com.test.grpc.order.Product getProducts(int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);
      } else {
        return productsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder setProducts(
        int index, com.test.grpc.order.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.set(index, value);
        onChanged();
      } else {
        productsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder setProducts(
        int index, com.test.grpc.order.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.set(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder addProducts(com.test.grpc.order.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(value);
        onChanged();
      } else {
        productsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder addProducts(
        int index, com.test.grpc.order.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(index, value);
        onChanged();
      } else {
        productsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder addProducts(
        com.test.grpc.order.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder addProducts(
        int index, com.test.grpc.order.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder addAllProducts(
        java.lang.Iterable<? extends com.test.grpc.order.Product> values) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, products_);
        onChanged();
      } else {
        productsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder clearProducts() {
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        productsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public Builder removeProducts(int index) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.remove(index);
        onChanged();
      } else {
        productsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public com.test.grpc.order.Product.Builder getProductsBuilder(
        int index) {
      return getProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public com.test.grpc.order.ProductOrBuilder getProductsOrBuilder(
        int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);  } else {
        return productsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public java.util.List<? extends com.test.grpc.order.ProductOrBuilder> 
         getProductsOrBuilderList() {
      if (productsBuilder_ != null) {
        return productsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(products_);
      }
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public com.test.grpc.order.Product.Builder addProductsBuilder() {
      return getProductsFieldBuilder().addBuilder(
          com.test.grpc.order.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public com.test.grpc.order.Product.Builder addProductsBuilder(
        int index) {
      return getProductsFieldBuilder().addBuilder(
          index, com.test.grpc.order.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .order.Product products = 1;</code>
     */
    public java.util.List<com.test.grpc.order.Product.Builder> 
         getProductsBuilderList() {
      return getProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.grpc.order.Product, com.test.grpc.order.Product.Builder, com.test.grpc.order.ProductOrBuilder> 
        getProductsFieldBuilder() {
      if (productsBuilder_ == null) {
        productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.test.grpc.order.Product, com.test.grpc.order.Product.Builder, com.test.grpc.order.ProductOrBuilder>(
                products_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        products_ = null;
      }
      return productsBuilder_;
    }

    private java.lang.Object userPid_ = "";
    /**
     * <code>string userPid = 2;</code>
     */
    public java.lang.String getUserPid() {
      java.lang.Object ref = userPid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userPid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserPidBytes() {
      java.lang.Object ref = userPid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userPid = 2;</code>
     */
    public Builder setUserPid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userPid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userPid = 2;</code>
     */
    public Builder clearUserPid() {
      
      userPid_ = getDefaultInstance().getUserPid();
      onChanged();
      return this;
    }
    /**
     * <code>string userPid = 2;</code>
     */
    public Builder setUserPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userPid_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue dateCreated_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> dateCreatedBuilder_;
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public boolean hasDateCreated() {
      return dateCreatedBuilder_ != null || dateCreated_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public com.google.protobuf.StringValue getDateCreated() {
      if (dateCreatedBuilder_ == null) {
        return dateCreated_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : dateCreated_;
      } else {
        return dateCreatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public Builder setDateCreated(com.google.protobuf.StringValue value) {
      if (dateCreatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateCreated_ = value;
        onChanged();
      } else {
        dateCreatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public Builder setDateCreated(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (dateCreatedBuilder_ == null) {
        dateCreated_ = builderForValue.build();
        onChanged();
      } else {
        dateCreatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public Builder mergeDateCreated(com.google.protobuf.StringValue value) {
      if (dateCreatedBuilder_ == null) {
        if (dateCreated_ != null) {
          dateCreated_ =
            com.google.protobuf.StringValue.newBuilder(dateCreated_).mergeFrom(value).buildPartial();
        } else {
          dateCreated_ = value;
        }
        onChanged();
      } else {
        dateCreatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public Builder clearDateCreated() {
      if (dateCreatedBuilder_ == null) {
        dateCreated_ = null;
        onChanged();
      } else {
        dateCreated_ = null;
        dateCreatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getDateCreatedBuilder() {
      
      onChanged();
      return getDateCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getDateCreatedOrBuilder() {
      if (dateCreatedBuilder_ != null) {
        return dateCreatedBuilder_.getMessageOrBuilder();
      } else {
        return dateCreated_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : dateCreated_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue dateCreated = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getDateCreatedFieldBuilder() {
      if (dateCreatedBuilder_ == null) {
        dateCreatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getDateCreated(),
                getParentForChildren(),
                isClean());
        dateCreated_ = null;
      }
      return dateCreatedBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.order.OrderStatus status = 4;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.order.OrderStatus status = 4;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.order.OrderStatus status = 4;</code>
     */
    public com.test.grpc.order.OrderStatus getStatus() {
      com.test.grpc.order.OrderStatus result = com.test.grpc.order.OrderStatus.valueOf(status_);
      return result == null ? com.test.grpc.order.OrderStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.order.OrderStatus status = 4;</code>
     */
    public Builder setStatus(com.test.grpc.order.OrderStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.order.OrderStatus status = 4;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private float pricePerUnit_ ;
    /**
     * <code>float pricePerUnit = 6;</code>
     */
    public float getPricePerUnit() {
      return pricePerUnit_;
    }
    /**
     * <code>float pricePerUnit = 6;</code>
     */
    public Builder setPricePerUnit(float value) {
      
      pricePerUnit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float pricePerUnit = 6;</code>
     */
    public Builder clearPricePerUnit() {
      
      pricePerUnit_ = 0F;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 7;</code>
     */
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 7;</code>
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 7;</code>
     */
    public Builder clearQuantity() {
      
      quantity_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue dateDelivered_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> dateDeliveredBuilder_;
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public boolean hasDateDelivered() {
      return dateDeliveredBuilder_ != null || dateDelivered_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public com.google.protobuf.StringValue getDateDelivered() {
      if (dateDeliveredBuilder_ == null) {
        return dateDelivered_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : dateDelivered_;
      } else {
        return dateDeliveredBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public Builder setDateDelivered(com.google.protobuf.StringValue value) {
      if (dateDeliveredBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateDelivered_ = value;
        onChanged();
      } else {
        dateDeliveredBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public Builder setDateDelivered(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (dateDeliveredBuilder_ == null) {
        dateDelivered_ = builderForValue.build();
        onChanged();
      } else {
        dateDeliveredBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public Builder mergeDateDelivered(com.google.protobuf.StringValue value) {
      if (dateDeliveredBuilder_ == null) {
        if (dateDelivered_ != null) {
          dateDelivered_ =
            com.google.protobuf.StringValue.newBuilder(dateDelivered_).mergeFrom(value).buildPartial();
        } else {
          dateDelivered_ = value;
        }
        onChanged();
      } else {
        dateDeliveredBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public Builder clearDateDelivered() {
      if (dateDeliveredBuilder_ == null) {
        dateDelivered_ = null;
        onChanged();
      } else {
        dateDelivered_ = null;
        dateDeliveredBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public com.google.protobuf.StringValue.Builder getDateDeliveredBuilder() {
      
      onChanged();
      return getDateDeliveredFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getDateDeliveredOrBuilder() {
      if (dateDeliveredBuilder_ != null) {
        return dateDeliveredBuilder_.getMessageOrBuilder();
      } else {
        return dateDelivered_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : dateDelivered_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue dateDelivered = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getDateDeliveredFieldBuilder() {
      if (dateDeliveredBuilder_ == null) {
        dateDeliveredBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getDateDelivered(),
                getParentForChildren(),
                isClean());
        dateDelivered_ = null;
      }
      return dateDeliveredBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:order.CreateOrderRequest)
  }

  // @@protoc_insertion_point(class_scope:order.CreateOrderRequest)
  private static final com.test.grpc.order.CreateOrderRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.grpc.order.CreateOrderRequest();
  }

  public static com.test.grpc.order.CreateOrderRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateOrderRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateOrderRequest>() {
    public CreateOrderRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateOrderRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateOrderRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateOrderRequest> getParserForType() {
    return PARSER;
  }

  public com.test.grpc.order.CreateOrderRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

