// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

public interface OrderUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue userPid = 1;</code>
   */
  boolean hasUserPid();
  /**
   * <code>.google.protobuf.StringValue userPid = 1;</code>
   */
  com.google.protobuf.StringValue getUserPid();
  /**
   * <code>.google.protobuf.StringValue userPid = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getUserPidOrBuilder();

  /**
   * <code>.google.protobuf.StringValue dateCreated = 2;</code>
   */
  boolean hasDateCreated();
  /**
   * <code>.google.protobuf.StringValue dateCreated = 2;</code>
   */
  com.google.protobuf.StringValue getDateCreated();
  /**
   * <code>.google.protobuf.StringValue dateCreated = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDateCreatedOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value status = 3;</code>
   */
  boolean hasStatus();
  /**
   * <code>.google.protobuf.Int32Value status = 3;</code>
   */
  com.google.protobuf.Int32Value getStatus();
  /**
   * <code>.google.protobuf.Int32Value status = 3;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getStatusOrBuilder();

  /**
   * <code>string pid = 4;</code>
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 4;</code>
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>.google.protobuf.StringValue deliveryDate = 5;</code>
   */
  boolean hasDeliveryDate();
  /**
   * <code>.google.protobuf.StringValue deliveryDate = 5;</code>
   */
  com.google.protobuf.StringValue getDeliveryDate();
  /**
   * <code>.google.protobuf.StringValue deliveryDate = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDeliveryDateOrBuilder();
}
