// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

/**
 * Protobuf type {@code order.OrderResponse}
 */
public  final class OrderResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:order.OrderResponse)
    OrderResponseOrBuilder {
  // Use OrderResponse.newBuilder() to construct.
  private OrderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderResponse() {
    pid_ = "";
    products_ = java.util.Collections.emptyList();
    userPid_ = "";
    dateCreated_ = "";
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OrderResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            pid_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              products_ = new java.util.ArrayList<com.test.grpc.order.Product>();
              mutable_bitField0_ |= 0x00000002;
            }
            products_.add(
                input.readMessage(com.test.grpc.order.Product.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userPid_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            dateCreated_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 50: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (deliveryDate_ != null) {
              subBuilder = deliveryDate_.toBuilder();
            }
            deliveryDate_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deliveryDate_);
              deliveryDate_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        products_ = java.util.Collections.unmodifiableList(products_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.grpc.order.Order.internal_static_order_OrderResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.grpc.order.Order.internal_static_order_OrderResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.grpc.order.OrderResponse.class, com.test.grpc.order.OrderResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PID_FIELD_NUMBER = 1;
  private volatile java.lang.Object pid_;
  /**
   * <code>string pid = 1;</code>
   */
  public java.lang.String getPid() {
    java.lang.Object ref = pid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pid_ = s;
      return s;
    }
  }
  /**
   * <code>string pid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPidBytes() {
    java.lang.Object ref = pid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTS_FIELD_NUMBER = 2;
  private java.util.List<com.test.grpc.order.Product> products_;
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  public java.util.List<com.test.grpc.order.Product> getProductsList() {
    return products_;
  }
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  public java.util.List<? extends com.test.grpc.order.ProductOrBuilder> 
      getProductsOrBuilderList() {
    return products_;
  }
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  public int getProductsCount() {
    return products_.size();
  }
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  public com.test.grpc.order.Product getProducts(int index) {
    return products_.get(index);
  }
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  public com.test.grpc.order.ProductOrBuilder getProductsOrBuilder(
      int index) {
    return products_.get(index);
  }

  public static final int USERPID_FIELD_NUMBER = 3;
  private volatile java.lang.Object userPid_;
  /**
   * <code>string userPid = 3;</code>
   */
  public java.lang.String getUserPid() {
    java.lang.Object ref = userPid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userPid_ = s;
      return s;
    }
  }
  /**
   * <code>string userPid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserPidBytes() {
    java.lang.Object ref = userPid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userPid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATECREATED_FIELD_NUMBER = 4;
  private volatile java.lang.Object dateCreated_;
  /**
   * <code>string dateCreated = 4;</code>
   */
  public java.lang.String getDateCreated() {
    java.lang.Object ref = dateCreated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateCreated_ = s;
      return s;
    }
  }
  /**
   * <code>string dateCreated = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDateCreatedBytes() {
    java.lang.Object ref = dateCreated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateCreated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_;
  /**
   * <code>.order.OrderStatus status = 5;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.order.OrderStatus status = 5;</code>
   */
  public com.test.grpc.order.OrderStatus getStatus() {
    com.test.grpc.order.OrderStatus result = com.test.grpc.order.OrderStatus.valueOf(status_);
    return result == null ? com.test.grpc.order.OrderStatus.UNRECOGNIZED : result;
  }

  public static final int DELIVERYDATE_FIELD_NUMBER = 6;
  private com.google.protobuf.StringValue deliveryDate_;
  /**
   * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
   */
  public boolean hasDeliveryDate() {
    return deliveryDate_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
   */
  public com.google.protobuf.StringValue getDeliveryDate() {
    return deliveryDate_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : deliveryDate_;
  }
  /**
   * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getDeliveryDateOrBuilder() {
    return getDeliveryDate();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pid_);
    }
    for (int i = 0; i < products_.size(); i++) {
      output.writeMessage(2, products_.get(i));
    }
    if (!getUserPidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPid_);
    }
    if (!getDateCreatedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dateCreated_);
    }
    if (status_ != com.test.grpc.order.OrderStatus.CREATED.getNumber()) {
      output.writeEnum(5, status_);
    }
    if (deliveryDate_ != null) {
      output.writeMessage(6, getDeliveryDate());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pid_);
    }
    for (int i = 0; i < products_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, products_.get(i));
    }
    if (!getUserPidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPid_);
    }
    if (!getDateCreatedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dateCreated_);
    }
    if (status_ != com.test.grpc.order.OrderStatus.CREATED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, status_);
    }
    if (deliveryDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDeliveryDate());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.grpc.order.OrderResponse)) {
      return super.equals(obj);
    }
    com.test.grpc.order.OrderResponse other = (com.test.grpc.order.OrderResponse) obj;

    boolean result = true;
    result = result && getPid()
        .equals(other.getPid());
    result = result && getProductsList()
        .equals(other.getProductsList());
    result = result && getUserPid()
        .equals(other.getUserPid());
    result = result && getDateCreated()
        .equals(other.getDateCreated());
    result = result && status_ == other.status_;
    result = result && (hasDeliveryDate() == other.hasDeliveryDate());
    if (hasDeliveryDate()) {
      result = result && getDeliveryDate()
          .equals(other.getDeliveryDate());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PID_FIELD_NUMBER;
    hash = (53 * hash) + getPid().hashCode();
    if (getProductsCount() > 0) {
      hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getProductsList().hashCode();
    }
    hash = (37 * hash) + USERPID_FIELD_NUMBER;
    hash = (53 * hash) + getUserPid().hashCode();
    hash = (37 * hash) + DATECREATED_FIELD_NUMBER;
    hash = (53 * hash) + getDateCreated().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasDeliveryDate()) {
      hash = (37 * hash) + DELIVERYDATE_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.grpc.order.OrderResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.OrderResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.OrderResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.OrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.grpc.order.OrderResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code order.OrderResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:order.OrderResponse)
      com.test.grpc.order.OrderResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.grpc.order.Order.internal_static_order_OrderResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.grpc.order.Order.internal_static_order_OrderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.grpc.order.OrderResponse.class, com.test.grpc.order.OrderResponse.Builder.class);
    }

    // Construct using com.test.grpc.order.OrderResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProductsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      pid_ = "";

      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        productsBuilder_.clear();
      }
      userPid_ = "";

      dateCreated_ = "";

      status_ = 0;

      if (deliveryDateBuilder_ == null) {
        deliveryDate_ = null;
      } else {
        deliveryDate_ = null;
        deliveryDateBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.grpc.order.Order.internal_static_order_OrderResponse_descriptor;
    }

    public com.test.grpc.order.OrderResponse getDefaultInstanceForType() {
      return com.test.grpc.order.OrderResponse.getDefaultInstance();
    }

    public com.test.grpc.order.OrderResponse build() {
      com.test.grpc.order.OrderResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.grpc.order.OrderResponse buildPartial() {
      com.test.grpc.order.OrderResponse result = new com.test.grpc.order.OrderResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.pid_ = pid_;
      if (productsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          products_ = java.util.Collections.unmodifiableList(products_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.products_ = products_;
      } else {
        result.products_ = productsBuilder_.build();
      }
      result.userPid_ = userPid_;
      result.dateCreated_ = dateCreated_;
      result.status_ = status_;
      if (deliveryDateBuilder_ == null) {
        result.deliveryDate_ = deliveryDate_;
      } else {
        result.deliveryDate_ = deliveryDateBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.grpc.order.OrderResponse) {
        return mergeFrom((com.test.grpc.order.OrderResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.grpc.order.OrderResponse other) {
      if (other == com.test.grpc.order.OrderResponse.getDefaultInstance()) return this;
      if (!other.getPid().isEmpty()) {
        pid_ = other.pid_;
        onChanged();
      }
      if (productsBuilder_ == null) {
        if (!other.products_.isEmpty()) {
          if (products_.isEmpty()) {
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureProductsIsMutable();
            products_.addAll(other.products_);
          }
          onChanged();
        }
      } else {
        if (!other.products_.isEmpty()) {
          if (productsBuilder_.isEmpty()) {
            productsBuilder_.dispose();
            productsBuilder_ = null;
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000002);
            productsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProductsFieldBuilder() : null;
          } else {
            productsBuilder_.addAllMessages(other.products_);
          }
        }
      }
      if (!other.getUserPid().isEmpty()) {
        userPid_ = other.userPid_;
        onChanged();
      }
      if (!other.getDateCreated().isEmpty()) {
        dateCreated_ = other.dateCreated_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasDeliveryDate()) {
        mergeDeliveryDate(other.getDeliveryDate());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.grpc.order.OrderResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.grpc.order.OrderResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object pid_ = "";
    /**
     * <code>string pid = 1;</code>
     */
    public java.lang.String getPid() {
      java.lang.Object ref = pid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPidBytes() {
      java.lang.Object ref = pid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pid = 1;</code>
     */
    public Builder setPid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pid = 1;</code>
     */
    public Builder clearPid() {
      
      pid_ = getDefaultInstance().getPid();
      onChanged();
      return this;
    }
    /**
     * <code>string pid = 1;</code>
     */
    public Builder setPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pid_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.test.grpc.order.Product> products_ =
      java.util.Collections.emptyList();
    private void ensureProductsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        products_ = new java.util.ArrayList<com.test.grpc.order.Product>(products_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.grpc.order.Product, com.test.grpc.order.Product.Builder, com.test.grpc.order.ProductOrBuilder> productsBuilder_;

    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public java.util.List<com.test.grpc.order.Product> getProductsList() {
      if (productsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(products_);
      } else {
        return productsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public int getProductsCount() {
      if (productsBuilder_ == null) {
        return products_.size();
      } else {
        return productsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public com.test.grpc.order.Product getProducts(int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);
      } else {
        return productsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder setProducts(
        int index, com.test.grpc.order.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.set(index, value);
        onChanged();
      } else {
        productsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder setProducts(
        int index, com.test.grpc.order.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.set(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder addProducts(com.test.grpc.order.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(value);
        onChanged();
      } else {
        productsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder addProducts(
        int index, com.test.grpc.order.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(index, value);
        onChanged();
      } else {
        productsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder addProducts(
        com.test.grpc.order.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder addProducts(
        int index, com.test.grpc.order.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder addAllProducts(
        java.lang.Iterable<? extends com.test.grpc.order.Product> values) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, products_);
        onChanged();
      } else {
        productsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder clearProducts() {
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        productsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public Builder removeProducts(int index) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.remove(index);
        onChanged();
      } else {
        productsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public com.test.grpc.order.Product.Builder getProductsBuilder(
        int index) {
      return getProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public com.test.grpc.order.ProductOrBuilder getProductsOrBuilder(
        int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);  } else {
        return productsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public java.util.List<? extends com.test.grpc.order.ProductOrBuilder> 
         getProductsOrBuilderList() {
      if (productsBuilder_ != null) {
        return productsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(products_);
      }
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public com.test.grpc.order.Product.Builder addProductsBuilder() {
      return getProductsFieldBuilder().addBuilder(
          com.test.grpc.order.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public com.test.grpc.order.Product.Builder addProductsBuilder(
        int index) {
      return getProductsFieldBuilder().addBuilder(
          index, com.test.grpc.order.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .order.Product products = 2;</code>
     */
    public java.util.List<com.test.grpc.order.Product.Builder> 
         getProductsBuilderList() {
      return getProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.grpc.order.Product, com.test.grpc.order.Product.Builder, com.test.grpc.order.ProductOrBuilder> 
        getProductsFieldBuilder() {
      if (productsBuilder_ == null) {
        productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.test.grpc.order.Product, com.test.grpc.order.Product.Builder, com.test.grpc.order.ProductOrBuilder>(
                products_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        products_ = null;
      }
      return productsBuilder_;
    }

    private java.lang.Object userPid_ = "";
    /**
     * <code>string userPid = 3;</code>
     */
    public java.lang.String getUserPid() {
      java.lang.Object ref = userPid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userPid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPidBytes() {
      java.lang.Object ref = userPid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userPid = 3;</code>
     */
    public Builder setUserPid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userPid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userPid = 3;</code>
     */
    public Builder clearUserPid() {
      
      userPid_ = getDefaultInstance().getUserPid();
      onChanged();
      return this;
    }
    /**
     * <code>string userPid = 3;</code>
     */
    public Builder setUserPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userPid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dateCreated_ = "";
    /**
     * <code>string dateCreated = 4;</code>
     */
    public java.lang.String getDateCreated() {
      java.lang.Object ref = dateCreated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateCreated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateCreated = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDateCreatedBytes() {
      java.lang.Object ref = dateCreated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateCreated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateCreated = 4;</code>
     */
    public Builder setDateCreated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateCreated = 4;</code>
     */
    public Builder clearDateCreated() {
      
      dateCreated_ = getDefaultInstance().getDateCreated();
      onChanged();
      return this;
    }
    /**
     * <code>string dateCreated = 4;</code>
     */
    public Builder setDateCreatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateCreated_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.order.OrderStatus status = 5;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.order.OrderStatus status = 5;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.order.OrderStatus status = 5;</code>
     */
    public com.test.grpc.order.OrderStatus getStatus() {
      com.test.grpc.order.OrderStatus result = com.test.grpc.order.OrderStatus.valueOf(status_);
      return result == null ? com.test.grpc.order.OrderStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.order.OrderStatus status = 5;</code>
     */
    public Builder setStatus(com.test.grpc.order.OrderStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.order.OrderStatus status = 5;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue deliveryDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> deliveryDateBuilder_;
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public boolean hasDeliveryDate() {
      return deliveryDateBuilder_ != null || deliveryDate_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public com.google.protobuf.StringValue getDeliveryDate() {
      if (deliveryDateBuilder_ == null) {
        return deliveryDate_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : deliveryDate_;
      } else {
        return deliveryDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public Builder setDeliveryDate(com.google.protobuf.StringValue value) {
      if (deliveryDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deliveryDate_ = value;
        onChanged();
      } else {
        deliveryDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public Builder setDeliveryDate(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (deliveryDateBuilder_ == null) {
        deliveryDate_ = builderForValue.build();
        onChanged();
      } else {
        deliveryDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public Builder mergeDeliveryDate(com.google.protobuf.StringValue value) {
      if (deliveryDateBuilder_ == null) {
        if (deliveryDate_ != null) {
          deliveryDate_ =
            com.google.protobuf.StringValue.newBuilder(deliveryDate_).mergeFrom(value).buildPartial();
        } else {
          deliveryDate_ = value;
        }
        onChanged();
      } else {
        deliveryDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public Builder clearDeliveryDate() {
      if (deliveryDateBuilder_ == null) {
        deliveryDate_ = null;
        onChanged();
      } else {
        deliveryDate_ = null;
        deliveryDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public com.google.protobuf.StringValue.Builder getDeliveryDateBuilder() {
      
      onChanged();
      return getDeliveryDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getDeliveryDateOrBuilder() {
      if (deliveryDateBuilder_ != null) {
        return deliveryDateBuilder_.getMessageOrBuilder();
      } else {
        return deliveryDate_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : deliveryDate_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getDeliveryDateFieldBuilder() {
      if (deliveryDateBuilder_ == null) {
        deliveryDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getDeliveryDate(),
                getParentForChildren(),
                isClean());
        deliveryDate_ = null;
      }
      return deliveryDateBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:order.OrderResponse)
  }

  // @@protoc_insertion_point(class_scope:order.OrderResponse)
  private static final com.test.grpc.order.OrderResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.grpc.order.OrderResponse();
  }

  public static com.test.grpc.order.OrderResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderResponse>
      PARSER = new com.google.protobuf.AbstractParser<OrderResponse>() {
    public OrderResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderResponse> getParserForType() {
    return PARSER;
  }

  public com.test.grpc.order.OrderResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

