// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

public interface OrderSearchFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderSearchFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  java.util.List<com.test.grpc.order.Product> 
      getProductsList();
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  com.test.grpc.order.Product getProducts(int index);
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  java.util.List<? extends com.test.grpc.order.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .order.Product products = 1;</code>
   */
  com.test.grpc.order.ProductOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.StringValue userPid = 2;</code>
   */
  boolean hasUserPid();
  /**
   * <code>.google.protobuf.StringValue userPid = 2;</code>
   */
  com.google.protobuf.StringValue getUserPid();
  /**
   * <code>.google.protobuf.StringValue userPid = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getUserPidOrBuilder();

  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  boolean hasDateCreated();
  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  com.google.protobuf.StringValue getDateCreated();
  /**
   * <code>.google.protobuf.StringValue dateCreated = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDateCreatedOrBuilder();

  /**
   * <code>.order.OrderStatus status = 4;</code>
   */
  int getStatusValue();
  /**
   * <code>.order.OrderStatus status = 4;</code>
   */
  com.test.grpc.order.OrderStatus getStatus();

  /**
   * <code>.google.protobuf.FloatValue pricePerUnit = 6;</code>
   */
  boolean hasPricePerUnit();
  /**
   * <code>.google.protobuf.FloatValue pricePerUnit = 6;</code>
   */
  com.google.protobuf.FloatValue getPricePerUnit();
  /**
   * <code>.google.protobuf.FloatValue pricePerUnit = 6;</code>
   */
  com.google.protobuf.FloatValueOrBuilder getPricePerUnitOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value quantity = 7;</code>
   */
  boolean hasQuantity();
  /**
   * <code>.google.protobuf.Int32Value quantity = 7;</code>
   */
  com.google.protobuf.Int32Value getQuantity();
  /**
   * <code>.google.protobuf.Int32Value quantity = 7;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getQuantityOrBuilder();

  /**
   * <code>.google.protobuf.StringValue pid = 8;</code>
   */
  boolean hasPid();
  /**
   * <code>.google.protobuf.StringValue pid = 8;</code>
   */
  com.google.protobuf.StringValue getPid();
  /**
   * <code>.google.protobuf.StringValue pid = 8;</code>
   */
  com.google.protobuf.StringValueOrBuilder getPidOrBuilder();
}
