// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

/**
 * Protobuf enum {@code order.OrderStatus}
 */
public enum OrderStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREATED = 0;</code>
   */
  CREATED(0),
  /**
   * <code>SHIPPED = 1;</code>
   */
  SHIPPED(1),
  /**
   * <code>DELIVERED = 2;</code>
   */
  DELIVERED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATED = 0;</code>
   */
  public static final int CREATED_VALUE = 0;
  /**
   * <code>SHIPPED = 1;</code>
   */
  public static final int SHIPPED_VALUE = 1;
  /**
   * <code>DELIVERED = 2;</code>
   */
  public static final int DELIVERED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrderStatus valueOf(int value) {
    return forNumber(value);
  }

  public static OrderStatus forNumber(int value) {
    switch (value) {
      case 0: return CREATED;
      case 1: return SHIPPED;
      case 2: return DELIVERED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrderStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderStatus>() {
          public OrderStatus findValueByNumber(int number) {
            return OrderStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.test.grpc.order.Order.getDescriptor().getEnumTypes().get(0);
  }

  private static final OrderStatus[] VALUES = values();

  public static OrderStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrderStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:order.OrderStatus)
}

