// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_StringsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_StringsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrdersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrdersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_CreateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_CreateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_AddProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_AddProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_RemoveProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_RemoveProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_UpdateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_UpdateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderSearchFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderSearchFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_PageableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_PageableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_PageableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_PageableResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021order/order.proto\022\005order\032\033google/proto" +
      "buf/empty.proto\032\036google/protobuf/wrapper" +
      "s.proto\"!\n\016StringsRequest\022\017\n\007request\030\001 \003" +
      "(\t\"6\n\016OrdersResponse\022$\n\006orders\030\001 \003(\0132\024.o" +
      "rder.OrderResponse\"\274\001\n\rOrderResponse\022\013\n\003" +
      "pid\030\001 \001(\t\022 \n\010products\030\002 \003(\0132\016.order.Prod" +
      "uct\022\017\n\007userPid\030\003 \001(\t\022\023\n\013dateCreated\030\004 \001(" +
      "\t\022\"\n\006status\030\005 \001(\0162\022.order.OrderStatus\0222\n" +
      "\014deliveryDate\030\006 \001(\0132\034.google.protobuf.St" +
      "ringValue\"\373\001\n\022CreateOrderRequest\022 \n\010prod",
      "ucts\030\001 \003(\0132\016.order.Product\022\017\n\007userPid\030\002 " +
      "\001(\t\0221\n\013dateCreated\030\003 \001(\0132\034.google.protob" +
      "uf.StringValue\022\"\n\006status\030\004 \001(\0162\022.order.O" +
      "rderStatus\022\024\n\014pricePerUnit\030\006 \001(\002\022\020\n\010quan" +
      "tity\030\007 \001(\005\0223\n\rdateDelivered\030\010 \001(\0132\034.goog" +
      "le.protobuf.StringValue\"\344\001\n\022OrderUpdateR" +
      "equest\022-\n\007userPid\030\001 \001(\0132\034.google.protobu" +
      "f.StringValue\0221\n\013dateCreated\030\002 \001(\0132\034.goo" +
      "gle.protobuf.StringValue\022+\n\006status\030\003 \001(\013" +
      "2\033.google.protobuf.Int32Value\022\013\n\003pid\030\004 \001",
      "(\t\0222\n\014deliveryDate\030\005 \001(\0132\034.google.protob" +
      "uf.StringValue\"F\n\021AddProductRequest\022\037\n\007p" +
      "roduct\030\001 \001(\0132\016.order.Product\022\020\n\010orderPid" +
      "\030\002 \001(\t\"<\n\024RemoveProductRequest\022\020\n\010orderP" +
      "id\030\001 \001(\t\022\022\n\nproductPid\030\002 \001(\t\"\237\001\n\024UpdateP" +
      "roductRequest\022-\n\010quantity\030\001 \001(\0132\033.google" +
      ".protobuf.Int32Value\0222\n\014pricePerUnit\030\002 \001" +
      "(\0132\034.google.protobuf.DoubleValue\022\020\n\010orde" +
      "rPid\030\003 \001(\t\022\022\n\nproductPid\030\004 \001(\t\"\310\002\n\021Order" +
      "SearchFilter\022 \n\010products\030\001 \003(\0132\016.order.P",
      "roduct\022-\n\007userPid\030\002 \001(\0132\034.google.protobu" +
      "f.StringValue\0221\n\013dateCreated\030\003 \001(\0132\034.goo" +
      "gle.protobuf.StringValue\022\"\n\006status\030\004 \001(\016" +
      "2\022.order.OrderStatus\0221\n\014pricePerUnit\030\006 \001" +
      "(\0132\033.google.protobuf.FloatValue\022-\n\010quant" +
      "ity\030\007 \001(\0132\033.google.protobuf.Int32Value\022)" +
      "\n\003pid\030\010 \001(\0132\034.google.protobuf.StringValu" +
      "e\">\n\007Product\022\013\n\003pid\030\001 \001(\t\022\020\n\010quantity\030\002 " +
      "\001(\005\022\024\n\014pricePerUnit\030\003 \001(\001\"w\n\017PageableReq" +
      "uest\0222\n\rnumberPerPage\030\001 \001(\0132\033.google.pro",
      "tobuf.Int64Value\0220\n\nlastItemId\030\002 \001(\0132\034.g" +
      "oogle.protobuf.StringValue\"\377\001\n\020PageableR" +
      "esponse\022\"\n\004data\030\001 \003(\0132\024.order.OrderRespo" +
      "nse\0222\n\rnumberPerPage\030\002 \001(\0132\033.google.prot" +
      "obuf.Int64Value\0220\n\nlastItemId\030\003 \001(\0132\034.go" +
      "ogle.protobuf.StringValue\022*\n\005total\030\004 \001(\013" +
      "2\033.google.protobuf.Int64Value\0225\n\020noOfIte" +
      "msInBatch\030\005 \001(\0132\033.google.protobuf.Int64V" +
      "alue*6\n\013OrderStatus\022\013\n\007CREATED\020\000\022\013\n\007SHIP" +
      "PED\020\001\022\r\n\tDELIVERED\020\0022\253\005\n\014OrderService\022>\n",
      "\013CreateOrder\022\031.order.CreateOrderRequest\032" +
      "\024.order.OrderResponse\022C\n\013DeleteOrder\022\034.g" +
      "oogle.protobuf.StringValue\032\026.google.prot" +
      "obuf.Empty\022C\n\rGetOrderByPid\022\034.google.pro" +
      "tobuf.StringValue\032\024.order.OrderResponse\022" +
      "?\n\017GetOrdersByPids\022\025.order.StringsReques" +
      "t\032\025.order.OrdersResponse\0229\n\006Search\022\030.ord" +
      "er.OrderSearchFilter\032\025.order.OrdersRespo" +
      "nse\022@\n\013UpdateOrder\022\031.order.OrderUpdateRe" +
      "quest\032\026.google.protobuf.Empty\022G\n\024getAllO",
      "rdersPageable\022\026.order.PageableRequest\032\027." +
      "order.PageableResponse\022D\n\rRemoveProduct\022" +
      "\033.order.RemoveProductRequest\032\026.google.pr" +
      "otobuf.Empty\022>\n\nAddProduct\022\030.order.AddPr" +
      "oductRequest\032\026.google.protobuf.Empty\022D\n\r" +
      "UpdateProduct\022\033.order.UpdateProductReque" +
      "st\032\026.google.protobuf.EmptyB\027\n\023com.test.g" +
      "rpc.orderP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_order_StringsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_StringsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_StringsRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_order_OrdersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_OrdersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrdersResponse_descriptor,
        new java.lang.String[] { "Orders", });
    internal_static_order_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_order_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderResponse_descriptor,
        new java.lang.String[] { "Pid", "Products", "UserPid", "DateCreated", "Status", "DeliveryDate", });
    internal_static_order_CreateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_order_CreateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_CreateOrderRequest_descriptor,
        new java.lang.String[] { "Products", "UserPid", "DateCreated", "Status", "PricePerUnit", "Quantity", "DateDelivered", });
    internal_static_order_OrderUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_order_OrderUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderUpdateRequest_descriptor,
        new java.lang.String[] { "UserPid", "DateCreated", "Status", "Pid", "DeliveryDate", });
    internal_static_order_AddProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_order_AddProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_AddProductRequest_descriptor,
        new java.lang.String[] { "Product", "OrderPid", });
    internal_static_order_RemoveProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_order_RemoveProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_RemoveProductRequest_descriptor,
        new java.lang.String[] { "OrderPid", "ProductPid", });
    internal_static_order_UpdateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_order_UpdateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_UpdateProductRequest_descriptor,
        new java.lang.String[] { "Quantity", "PricePerUnit", "OrderPid", "ProductPid", });
    internal_static_order_OrderSearchFilter_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_order_OrderSearchFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderSearchFilter_descriptor,
        new java.lang.String[] { "Products", "UserPid", "DateCreated", "Status", "PricePerUnit", "Quantity", "Pid", });
    internal_static_order_Product_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_order_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_Product_descriptor,
        new java.lang.String[] { "Pid", "Quantity", "PricePerUnit", });
    internal_static_order_PageableRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_order_PageableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_PageableRequest_descriptor,
        new java.lang.String[] { "NumberPerPage", "LastItemId", });
    internal_static_order_PageableResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_order_PageableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_PageableResponse_descriptor,
        new java.lang.String[] { "Data", "NumberPerPage", "LastItemId", "Total", "NoOfItemsInBatch", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
