// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 1;</code>
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  java.util.List<com.test.grpc.order.Product> 
      getProductsList();
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  com.test.grpc.order.Product getProducts(int index);
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  java.util.List<? extends com.test.grpc.order.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .order.Product products = 2;</code>
   */
  com.test.grpc.order.ProductOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>string userPid = 3;</code>
   */
  java.lang.String getUserPid();
  /**
   * <code>string userPid = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserPidBytes();

  /**
   * <code>string dateCreated = 4;</code>
   */
  java.lang.String getDateCreated();
  /**
   * <code>string dateCreated = 4;</code>
   */
  com.google.protobuf.ByteString
      getDateCreatedBytes();

  /**
   * <code>.order.OrderStatus status = 5;</code>
   */
  int getStatusValue();
  /**
   * <code>.order.OrderStatus status = 5;</code>
   */
  com.test.grpc.order.OrderStatus getStatus();

  /**
   * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
   */
  boolean hasDeliveryDate();
  /**
   * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
   */
  com.google.protobuf.StringValue getDeliveryDate();
  /**
   * <code>.google.protobuf.StringValue deliveryDate = 6;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDeliveryDateOrBuilder();
}
