// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

/**
 * Protobuf type {@code order.PageableRequest}
 */
public  final class PageableRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:order.PageableRequest)
    PageableRequestOrBuilder {
  // Use PageableRequest.newBuilder() to construct.
  private PageableRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PageableRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PageableRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (numberPerPage_ != null) {
              subBuilder = numberPerPage_.toBuilder();
            }
            numberPerPage_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(numberPerPage_);
              numberPerPage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (lastItemId_ != null) {
              subBuilder = lastItemId_.toBuilder();
            }
            lastItemId_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastItemId_);
              lastItemId_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.grpc.order.Order.internal_static_order_PageableRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.grpc.order.Order.internal_static_order_PageableRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.grpc.order.PageableRequest.class, com.test.grpc.order.PageableRequest.Builder.class);
  }

  public static final int NUMBERPERPAGE_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value numberPerPage_;
  /**
   * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
   */
  public boolean hasNumberPerPage() {
    return numberPerPage_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
   */
  public com.google.protobuf.Int64Value getNumberPerPage() {
    return numberPerPage_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : numberPerPage_;
  }
  /**
   * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getNumberPerPageOrBuilder() {
    return getNumberPerPage();
  }

  public static final int LASTITEMID_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue lastItemId_;
  /**
   * <code>.google.protobuf.StringValue lastItemId = 2;</code>
   */
  public boolean hasLastItemId() {
    return lastItemId_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue lastItemId = 2;</code>
   */
  public com.google.protobuf.StringValue getLastItemId() {
    return lastItemId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : lastItemId_;
  }
  /**
   * <code>.google.protobuf.StringValue lastItemId = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getLastItemIdOrBuilder() {
    return getLastItemId();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (numberPerPage_ != null) {
      output.writeMessage(1, getNumberPerPage());
    }
    if (lastItemId_ != null) {
      output.writeMessage(2, getLastItemId());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (numberPerPage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNumberPerPage());
    }
    if (lastItemId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLastItemId());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.grpc.order.PageableRequest)) {
      return super.equals(obj);
    }
    com.test.grpc.order.PageableRequest other = (com.test.grpc.order.PageableRequest) obj;

    boolean result = true;
    result = result && (hasNumberPerPage() == other.hasNumberPerPage());
    if (hasNumberPerPage()) {
      result = result && getNumberPerPage()
          .equals(other.getNumberPerPage());
    }
    result = result && (hasLastItemId() == other.hasLastItemId());
    if (hasLastItemId()) {
      result = result && getLastItemId()
          .equals(other.getLastItemId());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNumberPerPage()) {
      hash = (37 * hash) + NUMBERPERPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getNumberPerPage().hashCode();
    }
    if (hasLastItemId()) {
      hash = (37 * hash) + LASTITEMID_FIELD_NUMBER;
      hash = (53 * hash) + getLastItemId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.grpc.order.PageableRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.PageableRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.PageableRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.PageableRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.grpc.order.PageableRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code order.PageableRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:order.PageableRequest)
      com.test.grpc.order.PageableRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.grpc.order.Order.internal_static_order_PageableRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.grpc.order.Order.internal_static_order_PageableRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.grpc.order.PageableRequest.class, com.test.grpc.order.PageableRequest.Builder.class);
    }

    // Construct using com.test.grpc.order.PageableRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (numberPerPageBuilder_ == null) {
        numberPerPage_ = null;
      } else {
        numberPerPage_ = null;
        numberPerPageBuilder_ = null;
      }
      if (lastItemIdBuilder_ == null) {
        lastItemId_ = null;
      } else {
        lastItemId_ = null;
        lastItemIdBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.grpc.order.Order.internal_static_order_PageableRequest_descriptor;
    }

    public com.test.grpc.order.PageableRequest getDefaultInstanceForType() {
      return com.test.grpc.order.PageableRequest.getDefaultInstance();
    }

    public com.test.grpc.order.PageableRequest build() {
      com.test.grpc.order.PageableRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.grpc.order.PageableRequest buildPartial() {
      com.test.grpc.order.PageableRequest result = new com.test.grpc.order.PageableRequest(this);
      if (numberPerPageBuilder_ == null) {
        result.numberPerPage_ = numberPerPage_;
      } else {
        result.numberPerPage_ = numberPerPageBuilder_.build();
      }
      if (lastItemIdBuilder_ == null) {
        result.lastItemId_ = lastItemId_;
      } else {
        result.lastItemId_ = lastItemIdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.grpc.order.PageableRequest) {
        return mergeFrom((com.test.grpc.order.PageableRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.grpc.order.PageableRequest other) {
      if (other == com.test.grpc.order.PageableRequest.getDefaultInstance()) return this;
      if (other.hasNumberPerPage()) {
        mergeNumberPerPage(other.getNumberPerPage());
      }
      if (other.hasLastItemId()) {
        mergeLastItemId(other.getLastItemId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.grpc.order.PageableRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.grpc.order.PageableRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int64Value numberPerPage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> numberPerPageBuilder_;
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public boolean hasNumberPerPage() {
      return numberPerPageBuilder_ != null || numberPerPage_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public com.google.protobuf.Int64Value getNumberPerPage() {
      if (numberPerPageBuilder_ == null) {
        return numberPerPage_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : numberPerPage_;
      } else {
        return numberPerPageBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public Builder setNumberPerPage(com.google.protobuf.Int64Value value) {
      if (numberPerPageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        numberPerPage_ = value;
        onChanged();
      } else {
        numberPerPageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public Builder setNumberPerPage(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (numberPerPageBuilder_ == null) {
        numberPerPage_ = builderForValue.build();
        onChanged();
      } else {
        numberPerPageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public Builder mergeNumberPerPage(com.google.protobuf.Int64Value value) {
      if (numberPerPageBuilder_ == null) {
        if (numberPerPage_ != null) {
          numberPerPage_ =
            com.google.protobuf.Int64Value.newBuilder(numberPerPage_).mergeFrom(value).buildPartial();
        } else {
          numberPerPage_ = value;
        }
        onChanged();
      } else {
        numberPerPageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public Builder clearNumberPerPage() {
      if (numberPerPageBuilder_ == null) {
        numberPerPage_ = null;
        onChanged();
      } else {
        numberPerPage_ = null;
        numberPerPageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public com.google.protobuf.Int64Value.Builder getNumberPerPageBuilder() {
      
      onChanged();
      return getNumberPerPageFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getNumberPerPageOrBuilder() {
      if (numberPerPageBuilder_ != null) {
        return numberPerPageBuilder_.getMessageOrBuilder();
      } else {
        return numberPerPage_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : numberPerPage_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value numberPerPage = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getNumberPerPageFieldBuilder() {
      if (numberPerPageBuilder_ == null) {
        numberPerPageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getNumberPerPage(),
                getParentForChildren(),
                isClean());
        numberPerPage_ = null;
      }
      return numberPerPageBuilder_;
    }

    private com.google.protobuf.StringValue lastItemId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> lastItemIdBuilder_;
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public boolean hasLastItemId() {
      return lastItemIdBuilder_ != null || lastItemId_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public com.google.protobuf.StringValue getLastItemId() {
      if (lastItemIdBuilder_ == null) {
        return lastItemId_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : lastItemId_;
      } else {
        return lastItemIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public Builder setLastItemId(com.google.protobuf.StringValue value) {
      if (lastItemIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastItemId_ = value;
        onChanged();
      } else {
        lastItemIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public Builder setLastItemId(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (lastItemIdBuilder_ == null) {
        lastItemId_ = builderForValue.build();
        onChanged();
      } else {
        lastItemIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public Builder mergeLastItemId(com.google.protobuf.StringValue value) {
      if (lastItemIdBuilder_ == null) {
        if (lastItemId_ != null) {
          lastItemId_ =
            com.google.protobuf.StringValue.newBuilder(lastItemId_).mergeFrom(value).buildPartial();
        } else {
          lastItemId_ = value;
        }
        onChanged();
      } else {
        lastItemIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public Builder clearLastItemId() {
      if (lastItemIdBuilder_ == null) {
        lastItemId_ = null;
        onChanged();
      } else {
        lastItemId_ = null;
        lastItemIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getLastItemIdBuilder() {
      
      onChanged();
      return getLastItemIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getLastItemIdOrBuilder() {
      if (lastItemIdBuilder_ != null) {
        return lastItemIdBuilder_.getMessageOrBuilder();
      } else {
        return lastItemId_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : lastItemId_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue lastItemId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getLastItemIdFieldBuilder() {
      if (lastItemIdBuilder_ == null) {
        lastItemIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getLastItemId(),
                getParentForChildren(),
                isClean());
        lastItemId_ = null;
      }
      return lastItemIdBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:order.PageableRequest)
  }

  // @@protoc_insertion_point(class_scope:order.PageableRequest)
  private static final com.test.grpc.order.PageableRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.grpc.order.PageableRequest();
  }

  public static com.test.grpc.order.PageableRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PageableRequest>
      PARSER = new com.google.protobuf.AbstractParser<PageableRequest>() {
    public PageableRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageableRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PageableRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PageableRequest> getParserForType() {
    return PARSER;
  }

  public com.test.grpc.order.PageableRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

