// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order/order.proto

package com.test.grpc.order;

/**
 * Protobuf type {@code order.UpdateProductRequest}
 */
public  final class UpdateProductRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:order.UpdateProductRequest)
    UpdateProductRequestOrBuilder {
  // Use UpdateProductRequest.newBuilder() to construct.
  private UpdateProductRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateProductRequest() {
    orderPid_ = "";
    productPid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateProductRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (quantity_ != null) {
              subBuilder = quantity_.toBuilder();
            }
            quantity_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(quantity_);
              quantity_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (pricePerUnit_ != null) {
              subBuilder = pricePerUnit_.toBuilder();
            }
            pricePerUnit_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pricePerUnit_);
              pricePerUnit_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            orderPid_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            productPid_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.grpc.order.Order.internal_static_order_UpdateProductRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.grpc.order.Order.internal_static_order_UpdateProductRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.grpc.order.UpdateProductRequest.class, com.test.grpc.order.UpdateProductRequest.Builder.class);
  }

  public static final int QUANTITY_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value quantity_;
  /**
   * <code>.google.protobuf.Int32Value quantity = 1;</code>
   */
  public boolean hasQuantity() {
    return quantity_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value quantity = 1;</code>
   */
  public com.google.protobuf.Int32Value getQuantity() {
    return quantity_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : quantity_;
  }
  /**
   * <code>.google.protobuf.Int32Value quantity = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getQuantityOrBuilder() {
    return getQuantity();
  }

  public static final int PRICEPERUNIT_FIELD_NUMBER = 2;
  private com.google.protobuf.DoubleValue pricePerUnit_;
  /**
   * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
   */
  public boolean hasPricePerUnit() {
    return pricePerUnit_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
   */
  public com.google.protobuf.DoubleValue getPricePerUnit() {
    return pricePerUnit_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : pricePerUnit_;
  }
  /**
   * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
   */
  public com.google.protobuf.DoubleValueOrBuilder getPricePerUnitOrBuilder() {
    return getPricePerUnit();
  }

  public static final int ORDERPID_FIELD_NUMBER = 3;
  private volatile java.lang.Object orderPid_;
  /**
   * <code>string orderPid = 3;</code>
   */
  public java.lang.String getOrderPid() {
    java.lang.Object ref = orderPid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderPid_ = s;
      return s;
    }
  }
  /**
   * <code>string orderPid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOrderPidBytes() {
    java.lang.Object ref = orderPid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderPid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTPID_FIELD_NUMBER = 4;
  private volatile java.lang.Object productPid_;
  /**
   * <code>string productPid = 4;</code>
   */
  public java.lang.String getProductPid() {
    java.lang.Object ref = productPid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productPid_ = s;
      return s;
    }
  }
  /**
   * <code>string productPid = 4;</code>
   */
  public com.google.protobuf.ByteString
      getProductPidBytes() {
    java.lang.Object ref = productPid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productPid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (quantity_ != null) {
      output.writeMessage(1, getQuantity());
    }
    if (pricePerUnit_ != null) {
      output.writeMessage(2, getPricePerUnit());
    }
    if (!getOrderPidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orderPid_);
    }
    if (!getProductPidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, productPid_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (quantity_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getQuantity());
    }
    if (pricePerUnit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPricePerUnit());
    }
    if (!getOrderPidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, orderPid_);
    }
    if (!getProductPidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, productPid_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.grpc.order.UpdateProductRequest)) {
      return super.equals(obj);
    }
    com.test.grpc.order.UpdateProductRequest other = (com.test.grpc.order.UpdateProductRequest) obj;

    boolean result = true;
    result = result && (hasQuantity() == other.hasQuantity());
    if (hasQuantity()) {
      result = result && getQuantity()
          .equals(other.getQuantity());
    }
    result = result && (hasPricePerUnit() == other.hasPricePerUnit());
    if (hasPricePerUnit()) {
      result = result && getPricePerUnit()
          .equals(other.getPricePerUnit());
    }
    result = result && getOrderPid()
        .equals(other.getOrderPid());
    result = result && getProductPid()
        .equals(other.getProductPid());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity().hashCode();
    }
    if (hasPricePerUnit()) {
      hash = (37 * hash) + PRICEPERUNIT_FIELD_NUMBER;
      hash = (53 * hash) + getPricePerUnit().hashCode();
    }
    hash = (37 * hash) + ORDERPID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderPid().hashCode();
    hash = (37 * hash) + PRODUCTPID_FIELD_NUMBER;
    hash = (53 * hash) + getProductPid().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.UpdateProductRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.UpdateProductRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.order.UpdateProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.grpc.order.UpdateProductRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code order.UpdateProductRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:order.UpdateProductRequest)
      com.test.grpc.order.UpdateProductRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.grpc.order.Order.internal_static_order_UpdateProductRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.grpc.order.Order.internal_static_order_UpdateProductRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.grpc.order.UpdateProductRequest.class, com.test.grpc.order.UpdateProductRequest.Builder.class);
    }

    // Construct using com.test.grpc.order.UpdateProductRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (quantityBuilder_ == null) {
        quantity_ = null;
      } else {
        quantity_ = null;
        quantityBuilder_ = null;
      }
      if (pricePerUnitBuilder_ == null) {
        pricePerUnit_ = null;
      } else {
        pricePerUnit_ = null;
        pricePerUnitBuilder_ = null;
      }
      orderPid_ = "";

      productPid_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.grpc.order.Order.internal_static_order_UpdateProductRequest_descriptor;
    }

    public com.test.grpc.order.UpdateProductRequest getDefaultInstanceForType() {
      return com.test.grpc.order.UpdateProductRequest.getDefaultInstance();
    }

    public com.test.grpc.order.UpdateProductRequest build() {
      com.test.grpc.order.UpdateProductRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.grpc.order.UpdateProductRequest buildPartial() {
      com.test.grpc.order.UpdateProductRequest result = new com.test.grpc.order.UpdateProductRequest(this);
      if (quantityBuilder_ == null) {
        result.quantity_ = quantity_;
      } else {
        result.quantity_ = quantityBuilder_.build();
      }
      if (pricePerUnitBuilder_ == null) {
        result.pricePerUnit_ = pricePerUnit_;
      } else {
        result.pricePerUnit_ = pricePerUnitBuilder_.build();
      }
      result.orderPid_ = orderPid_;
      result.productPid_ = productPid_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.grpc.order.UpdateProductRequest) {
        return mergeFrom((com.test.grpc.order.UpdateProductRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.grpc.order.UpdateProductRequest other) {
      if (other == com.test.grpc.order.UpdateProductRequest.getDefaultInstance()) return this;
      if (other.hasQuantity()) {
        mergeQuantity(other.getQuantity());
      }
      if (other.hasPricePerUnit()) {
        mergePricePerUnit(other.getPricePerUnit());
      }
      if (!other.getOrderPid().isEmpty()) {
        orderPid_ = other.orderPid_;
        onChanged();
      }
      if (!other.getProductPid().isEmpty()) {
        productPid_ = other.productPid_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.grpc.order.UpdateProductRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.grpc.order.UpdateProductRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int32Value quantity_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> quantityBuilder_;
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public boolean hasQuantity() {
      return quantityBuilder_ != null || quantity_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public com.google.protobuf.Int32Value getQuantity() {
      if (quantityBuilder_ == null) {
        return quantity_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : quantity_;
      } else {
        return quantityBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public Builder setQuantity(com.google.protobuf.Int32Value value) {
      if (quantityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        quantity_ = value;
        onChanged();
      } else {
        quantityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public Builder setQuantity(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (quantityBuilder_ == null) {
        quantity_ = builderForValue.build();
        onChanged();
      } else {
        quantityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public Builder mergeQuantity(com.google.protobuf.Int32Value value) {
      if (quantityBuilder_ == null) {
        if (quantity_ != null) {
          quantity_ =
            com.google.protobuf.Int32Value.newBuilder(quantity_).mergeFrom(value).buildPartial();
        } else {
          quantity_ = value;
        }
        onChanged();
      } else {
        quantityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public Builder clearQuantity() {
      if (quantityBuilder_ == null) {
        quantity_ = null;
        onChanged();
      } else {
        quantity_ = null;
        quantityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getQuantityBuilder() {
      
      onChanged();
      return getQuantityFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getQuantityOrBuilder() {
      if (quantityBuilder_ != null) {
        return quantityBuilder_.getMessageOrBuilder();
      } else {
        return quantity_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : quantity_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value quantity = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getQuantityFieldBuilder() {
      if (quantityBuilder_ == null) {
        quantityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getQuantity(),
                getParentForChildren(),
                isClean());
        quantity_ = null;
      }
      return quantityBuilder_;
    }

    private com.google.protobuf.DoubleValue pricePerUnit_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> pricePerUnitBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public boolean hasPricePerUnit() {
      return pricePerUnitBuilder_ != null || pricePerUnit_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public com.google.protobuf.DoubleValue getPricePerUnit() {
      if (pricePerUnitBuilder_ == null) {
        return pricePerUnit_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : pricePerUnit_;
      } else {
        return pricePerUnitBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public Builder setPricePerUnit(com.google.protobuf.DoubleValue value) {
      if (pricePerUnitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pricePerUnit_ = value;
        onChanged();
      } else {
        pricePerUnitBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public Builder setPricePerUnit(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (pricePerUnitBuilder_ == null) {
        pricePerUnit_ = builderForValue.build();
        onChanged();
      } else {
        pricePerUnitBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public Builder mergePricePerUnit(com.google.protobuf.DoubleValue value) {
      if (pricePerUnitBuilder_ == null) {
        if (pricePerUnit_ != null) {
          pricePerUnit_ =
            com.google.protobuf.DoubleValue.newBuilder(pricePerUnit_).mergeFrom(value).buildPartial();
        } else {
          pricePerUnit_ = value;
        }
        onChanged();
      } else {
        pricePerUnitBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public Builder clearPricePerUnit() {
      if (pricePerUnitBuilder_ == null) {
        pricePerUnit_ = null;
        onChanged();
      } else {
        pricePerUnit_ = null;
        pricePerUnitBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getPricePerUnitBuilder() {
      
      onChanged();
      return getPricePerUnitFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getPricePerUnitOrBuilder() {
      if (pricePerUnitBuilder_ != null) {
        return pricePerUnitBuilder_.getMessageOrBuilder();
      } else {
        return pricePerUnit_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : pricePerUnit_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue pricePerUnit = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getPricePerUnitFieldBuilder() {
      if (pricePerUnitBuilder_ == null) {
        pricePerUnitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getPricePerUnit(),
                getParentForChildren(),
                isClean());
        pricePerUnit_ = null;
      }
      return pricePerUnitBuilder_;
    }

    private java.lang.Object orderPid_ = "";
    /**
     * <code>string orderPid = 3;</code>
     */
    public java.lang.String getOrderPid() {
      java.lang.Object ref = orderPid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderPid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orderPid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrderPidBytes() {
      java.lang.Object ref = orderPid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderPid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orderPid = 3;</code>
     */
    public Builder setOrderPid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderPid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orderPid = 3;</code>
     */
    public Builder clearOrderPid() {
      
      orderPid_ = getDefaultInstance().getOrderPid();
      onChanged();
      return this;
    }
    /**
     * <code>string orderPid = 3;</code>
     */
    public Builder setOrderPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderPid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productPid_ = "";
    /**
     * <code>string productPid = 4;</code>
     */
    public java.lang.String getProductPid() {
      java.lang.Object ref = productPid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productPid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productPid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProductPidBytes() {
      java.lang.Object ref = productPid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productPid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productPid = 4;</code>
     */
    public Builder setProductPid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productPid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productPid = 4;</code>
     */
    public Builder clearProductPid() {
      
      productPid_ = getDefaultInstance().getProductPid();
      onChanged();
      return this;
    }
    /**
     * <code>string productPid = 4;</code>
     */
    public Builder setProductPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productPid_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:order.UpdateProductRequest)
  }

  // @@protoc_insertion_point(class_scope:order.UpdateProductRequest)
  private static final com.test.grpc.order.UpdateProductRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.grpc.order.UpdateProductRequest();
  }

  public static com.test.grpc.order.UpdateProductRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateProductRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateProductRequest>() {
    public UpdateProductRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateProductRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateProductRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateProductRequest> getParserForType() {
    return PARSER;
  }

  public com.test.grpc.order.UpdateProductRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

