// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpc;

public interface CreateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.CreateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue fullName = 1;</code>
   */
  boolean hasFullName();
  /**
   * <code>.google.protobuf.StringValue fullName = 1;</code>
   */
  com.google.protobuf.StringValue getFullName();
  /**
   * <code>.google.protobuf.StringValue fullName = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getFullNameOrBuilder();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  boolean hasAddress();
  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  com.test.grpc.ShippingAddress getAddress();
  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  com.test.grpc.ShippingAddressOrBuilder getAddressOrBuilder();

  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  java.util.List<com.test.grpc.PaymentMethod> 
      getPaymentMethodsList();
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  com.test.grpc.PaymentMethod getPaymentMethods(int index);
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  int getPaymentMethodsCount();
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  java.util.List<? extends com.test.grpc.PaymentMethodOrBuilder> 
      getPaymentMethodsOrBuilderList();
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  com.test.grpc.PaymentMethodOrBuilder getPaymentMethodsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.StringValue password = 5;</code>
   */
  boolean hasPassword();
  /**
   * <code>.google.protobuf.StringValue password = 5;</code>
   */
  com.google.protobuf.StringValue getPassword();
  /**
   * <code>.google.protobuf.StringValue password = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getPasswordOrBuilder();
}
