// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpc;

/**
 * Protobuf type {@code user.CreateUserRequest}
 */
public  final class CreateUserRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.CreateUserRequest)
    CreateUserRequestOrBuilder {
  // Use CreateUserRequest.newBuilder() to construct.
  private CreateUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  public CreateUserRequest() {
    email_ = "";
    paymentMethods_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  public CreateUserRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (fullName_ != null) {
              subBuilder = fullName_.toBuilder();
            }
            fullName_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fullName_);
              fullName_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 26: {
            com.test.grpc.ShippingAddress.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(com.test.grpc.ShippingAddress.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              paymentMethods_ = new java.util.ArrayList<com.test.grpc.PaymentMethod>();
              mutable_bitField0_ |= 0x00000008;
            }
            paymentMethods_.add(
                input.readMessage(com.test.grpc.PaymentMethod.parser(), extensionRegistry));
            break;
          }
          case 42: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (password_ != null) {
              subBuilder = password_.toBuilder();
            }
            password_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(password_);
              password_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        paymentMethods_ = java.util.Collections.unmodifiableList(paymentMethods_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.grpc.User.internal_static_user_CreateUserRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.grpc.User.internal_static_user_CreateUserRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.grpc.CreateUserRequest.class, com.test.grpc.CreateUserRequest.Builder.class);
  }

  private int bitField0_;
  public static final int FULLNAME_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue fullName_;
  /**
   * <code>.google.protobuf.StringValue fullName = 1;</code>
   */
  public boolean hasFullName() {
    return fullName_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue fullName = 1;</code>
   */
  public com.google.protobuf.StringValue getFullName() {
    return fullName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : fullName_;
  }
  /**
   * <code>.google.protobuf.StringValue fullName = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getFullNameOrBuilder() {
    return getFullName();
  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 2;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private com.test.grpc.ShippingAddress address_;
  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  public com.test.grpc.ShippingAddress getAddress() {
    return address_ == null ? com.test.grpc.ShippingAddress.getDefaultInstance() : address_;
  }
  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  public com.test.grpc.ShippingAddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int PAYMENTMETHODS_FIELD_NUMBER = 4;
  private java.util.List<com.test.grpc.PaymentMethod> paymentMethods_;
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  public java.util.List<com.test.grpc.PaymentMethod> getPaymentMethodsList() {
    return paymentMethods_;
  }
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  public java.util.List<? extends com.test.grpc.PaymentMethodOrBuilder> 
      getPaymentMethodsOrBuilderList() {
    return paymentMethods_;
  }
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  public int getPaymentMethodsCount() {
    return paymentMethods_.size();
  }
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  public com.test.grpc.PaymentMethod getPaymentMethods(int index) {
    return paymentMethods_.get(index);
  }
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
   */
  public com.test.grpc.PaymentMethodOrBuilder getPaymentMethodsOrBuilder(
      int index) {
    return paymentMethods_.get(index);
  }

  public static final int PASSWORD_FIELD_NUMBER = 5;
  private com.google.protobuf.StringValue password_;
  /**
   * <code>.google.protobuf.StringValue password = 5;</code>
   */
  public boolean hasPassword() {
    return password_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue password = 5;</code>
   */
  public com.google.protobuf.StringValue getPassword() {
    return password_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : password_;
  }
  /**
   * <code>.google.protobuf.StringValue password = 5;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getPasswordOrBuilder() {
    return getPassword();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fullName_ != null) {
      output.writeMessage(1, getFullName());
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
    }
    if (address_ != null) {
      output.writeMessage(3, getAddress());
    }
    for (int i = 0; i < paymentMethods_.size(); i++) {
      output.writeMessage(4, paymentMethods_.get(i));
    }
    if (password_ != null) {
      output.writeMessage(5, getPassword());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fullName_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFullName());
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAddress());
    }
    for (int i = 0; i < paymentMethods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, paymentMethods_.get(i));
    }
    if (password_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPassword());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.grpc.CreateUserRequest)) {
      return super.equals(obj);
    }
    com.test.grpc.CreateUserRequest other = (com.test.grpc.CreateUserRequest) obj;

    boolean result = true;
    result = result && (hasFullName() == other.hasFullName());
    if (hasFullName()) {
      result = result && getFullName()
          .equals(other.getFullName());
    }
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && (hasAddress() == other.hasAddress());
    if (hasAddress()) {
      result = result && getAddress()
          .equals(other.getAddress());
    }
    result = result && getPaymentMethodsList()
        .equals(other.getPaymentMethodsList());
    result = result && (hasPassword() == other.hasPassword());
    if (hasPassword()) {
      result = result && getPassword()
          .equals(other.getPassword());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFullName()) {
      hash = (37 * hash) + FULLNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFullName().hashCode();
    }
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (getPaymentMethodsCount() > 0) {
      hash = (37 * hash) + PAYMENTMETHODS_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentMethodsList().hashCode();
    }
    if (hasPassword()) {
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.grpc.CreateUserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.CreateUserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.grpc.CreateUserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.CreateUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.grpc.CreateUserRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.CreateUserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.CreateUserRequest)
      com.test.grpc.CreateUserRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.grpc.User.internal_static_user_CreateUserRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.grpc.User.internal_static_user_CreateUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.grpc.CreateUserRequest.class, com.test.grpc.CreateUserRequest.Builder.class);
    }

    // Construct using com.test.grpc.CreateUserRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPaymentMethodsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (fullNameBuilder_ == null) {
        fullName_ = null;
      } else {
        fullName_ = null;
        fullNameBuilder_ = null;
      }
      email_ = "";

      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      if (paymentMethodsBuilder_ == null) {
        paymentMethods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        paymentMethodsBuilder_.clear();
      }
      if (passwordBuilder_ == null) {
        password_ = null;
      } else {
        password_ = null;
        passwordBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.grpc.User.internal_static_user_CreateUserRequest_descriptor;
    }

    public com.test.grpc.CreateUserRequest getDefaultInstanceForType() {
      return com.test.grpc.CreateUserRequest.getDefaultInstance();
    }

    public com.test.grpc.CreateUserRequest build() {
      com.test.grpc.CreateUserRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.grpc.CreateUserRequest buildPartial() {
      com.test.grpc.CreateUserRequest result = new com.test.grpc.CreateUserRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (fullNameBuilder_ == null) {
        result.fullName_ = fullName_;
      } else {
        result.fullName_ = fullNameBuilder_.build();
      }
      result.email_ = email_;
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      if (paymentMethodsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          paymentMethods_ = java.util.Collections.unmodifiableList(paymentMethods_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.paymentMethods_ = paymentMethods_;
      } else {
        result.paymentMethods_ = paymentMethodsBuilder_.build();
      }
      if (passwordBuilder_ == null) {
        result.password_ = password_;
      } else {
        result.password_ = passwordBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.grpc.CreateUserRequest) {
        return mergeFrom((com.test.grpc.CreateUserRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.grpc.CreateUserRequest other) {
      if (other == com.test.grpc.CreateUserRequest.getDefaultInstance()) return this;
      if (other.hasFullName()) {
        mergeFullName(other.getFullName());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (paymentMethodsBuilder_ == null) {
        if (!other.paymentMethods_.isEmpty()) {
          if (paymentMethods_.isEmpty()) {
            paymentMethods_ = other.paymentMethods_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePaymentMethodsIsMutable();
            paymentMethods_.addAll(other.paymentMethods_);
          }
          onChanged();
        }
      } else {
        if (!other.paymentMethods_.isEmpty()) {
          if (paymentMethodsBuilder_.isEmpty()) {
            paymentMethodsBuilder_.dispose();
            paymentMethodsBuilder_ = null;
            paymentMethods_ = other.paymentMethods_;
            bitField0_ = (bitField0_ & ~0x00000008);
            paymentMethodsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPaymentMethodsFieldBuilder() : null;
          } else {
            paymentMethodsBuilder_.addAllMessages(other.paymentMethods_);
          }
        }
      }
      if (other.hasPassword()) {
        mergePassword(other.getPassword());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.grpc.CreateUserRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.grpc.CreateUserRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.StringValue fullName_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> fullNameBuilder_;
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public boolean hasFullName() {
      return fullNameBuilder_ != null || fullName_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public com.google.protobuf.StringValue getFullName() {
      if (fullNameBuilder_ == null) {
        return fullName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : fullName_;
      } else {
        return fullNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public Builder setFullName(com.google.protobuf.StringValue value) {
      if (fullNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fullName_ = value;
        onChanged();
      } else {
        fullNameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public Builder setFullName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (fullNameBuilder_ == null) {
        fullName_ = builderForValue.build();
        onChanged();
      } else {
        fullNameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public Builder mergeFullName(com.google.protobuf.StringValue value) {
      if (fullNameBuilder_ == null) {
        if (fullName_ != null) {
          fullName_ =
            com.google.protobuf.StringValue.newBuilder(fullName_).mergeFrom(value).buildPartial();
        } else {
          fullName_ = value;
        }
        onChanged();
      } else {
        fullNameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public Builder clearFullName() {
      if (fullNameBuilder_ == null) {
        fullName_ = null;
        onChanged();
      } else {
        fullName_ = null;
        fullNameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getFullNameBuilder() {
      
      onChanged();
      return getFullNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getFullNameOrBuilder() {
      if (fullNameBuilder_ != null) {
        return fullNameBuilder_.getMessageOrBuilder();
      } else {
        return fullName_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : fullName_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue fullName = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getFullNameFieldBuilder() {
      if (fullNameBuilder_ == null) {
        fullNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getFullName(),
                getParentForChildren(),
                isClean());
        fullName_ = null;
      }
      return fullNameBuilder_;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private com.test.grpc.ShippingAddress address_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.test.grpc.ShippingAddress, com.test.grpc.ShippingAddress.Builder, com.test.grpc.ShippingAddressOrBuilder> addressBuilder_;
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public com.test.grpc.ShippingAddress getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? com.test.grpc.ShippingAddress.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public Builder setAddress(com.test.grpc.ShippingAddress value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public Builder setAddress(
        com.test.grpc.ShippingAddress.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public Builder mergeAddress(com.test.grpc.ShippingAddress value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            com.test.grpc.ShippingAddress.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public com.test.grpc.ShippingAddress.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    public com.test.grpc.ShippingAddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            com.test.grpc.ShippingAddress.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.user.ShippingAddress address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.test.grpc.ShippingAddress, com.test.grpc.ShippingAddress.Builder, com.test.grpc.ShippingAddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.test.grpc.ShippingAddress, com.test.grpc.ShippingAddress.Builder, com.test.grpc.ShippingAddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private java.util.List<com.test.grpc.PaymentMethod> paymentMethods_ =
      java.util.Collections.emptyList();
    private void ensurePaymentMethodsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        paymentMethods_ = new java.util.ArrayList<com.test.grpc.PaymentMethod>(paymentMethods_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.grpc.PaymentMethod, com.test.grpc.PaymentMethod.Builder, com.test.grpc.PaymentMethodOrBuilder> paymentMethodsBuilder_;

    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public java.util.List<com.test.grpc.PaymentMethod> getPaymentMethodsList() {
      if (paymentMethodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(paymentMethods_);
      } else {
        return paymentMethodsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public int getPaymentMethodsCount() {
      if (paymentMethodsBuilder_ == null) {
        return paymentMethods_.size();
      } else {
        return paymentMethodsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public com.test.grpc.PaymentMethod getPaymentMethods(int index) {
      if (paymentMethodsBuilder_ == null) {
        return paymentMethods_.get(index);
      } else {
        return paymentMethodsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder setPaymentMethods(
        int index, com.test.grpc.PaymentMethod value) {
      if (paymentMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaymentMethodsIsMutable();
        paymentMethods_.set(index, value);
        onChanged();
      } else {
        paymentMethodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder setPaymentMethods(
        int index, com.test.grpc.PaymentMethod.Builder builderForValue) {
      if (paymentMethodsBuilder_ == null) {
        ensurePaymentMethodsIsMutable();
        paymentMethods_.set(index, builderForValue.build());
        onChanged();
      } else {
        paymentMethodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder addPaymentMethods(com.test.grpc.PaymentMethod value) {
      if (paymentMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaymentMethodsIsMutable();
        paymentMethods_.add(value);
        onChanged();
      } else {
        paymentMethodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder addPaymentMethods(
        int index, com.test.grpc.PaymentMethod value) {
      if (paymentMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaymentMethodsIsMutable();
        paymentMethods_.add(index, value);
        onChanged();
      } else {
        paymentMethodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder addPaymentMethods(
        com.test.grpc.PaymentMethod.Builder builderForValue) {
      if (paymentMethodsBuilder_ == null) {
        ensurePaymentMethodsIsMutable();
        paymentMethods_.add(builderForValue.build());
        onChanged();
      } else {
        paymentMethodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder addPaymentMethods(
        int index, com.test.grpc.PaymentMethod.Builder builderForValue) {
      if (paymentMethodsBuilder_ == null) {
        ensurePaymentMethodsIsMutable();
        paymentMethods_.add(index, builderForValue.build());
        onChanged();
      } else {
        paymentMethodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder addAllPaymentMethods(
        java.lang.Iterable<? extends com.test.grpc.PaymentMethod> values) {
      if (paymentMethodsBuilder_ == null) {
        ensurePaymentMethodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paymentMethods_);
        onChanged();
      } else {
        paymentMethodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder clearPaymentMethods() {
      if (paymentMethodsBuilder_ == null) {
        paymentMethods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        paymentMethodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public Builder removePaymentMethods(int index) {
      if (paymentMethodsBuilder_ == null) {
        ensurePaymentMethodsIsMutable();
        paymentMethods_.remove(index);
        onChanged();
      } else {
        paymentMethodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public com.test.grpc.PaymentMethod.Builder getPaymentMethodsBuilder(
        int index) {
      return getPaymentMethodsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public com.test.grpc.PaymentMethodOrBuilder getPaymentMethodsOrBuilder(
        int index) {
      if (paymentMethodsBuilder_ == null) {
        return paymentMethods_.get(index);  } else {
        return paymentMethodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public java.util.List<? extends com.test.grpc.PaymentMethodOrBuilder> 
         getPaymentMethodsOrBuilderList() {
      if (paymentMethodsBuilder_ != null) {
        return paymentMethodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(paymentMethods_);
      }
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public com.test.grpc.PaymentMethod.Builder addPaymentMethodsBuilder() {
      return getPaymentMethodsFieldBuilder().addBuilder(
          com.test.grpc.PaymentMethod.getDefaultInstance());
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public com.test.grpc.PaymentMethod.Builder addPaymentMethodsBuilder(
        int index) {
      return getPaymentMethodsFieldBuilder().addBuilder(
          index, com.test.grpc.PaymentMethod.getDefaultInstance());
    }
    /**
     * <code>repeated .user.PaymentMethod paymentMethods = 4;</code>
     */
    public java.util.List<com.test.grpc.PaymentMethod.Builder> 
         getPaymentMethodsBuilderList() {
      return getPaymentMethodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.test.grpc.PaymentMethod, com.test.grpc.PaymentMethod.Builder, com.test.grpc.PaymentMethodOrBuilder> 
        getPaymentMethodsFieldBuilder() {
      if (paymentMethodsBuilder_ == null) {
        paymentMethodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.test.grpc.PaymentMethod, com.test.grpc.PaymentMethod.Builder, com.test.grpc.PaymentMethodOrBuilder>(
                paymentMethods_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        paymentMethods_ = null;
      }
      return paymentMethodsBuilder_;
    }

    private com.google.protobuf.StringValue password_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> passwordBuilder_;
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public boolean hasPassword() {
      return passwordBuilder_ != null || password_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public com.google.protobuf.StringValue getPassword() {
      if (passwordBuilder_ == null) {
        return password_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : password_;
      } else {
        return passwordBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public Builder setPassword(com.google.protobuf.StringValue value) {
      if (passwordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        password_ = value;
        onChanged();
      } else {
        passwordBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public Builder setPassword(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (passwordBuilder_ == null) {
        password_ = builderForValue.build();
        onChanged();
      } else {
        passwordBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public Builder mergePassword(com.google.protobuf.StringValue value) {
      if (passwordBuilder_ == null) {
        if (password_ != null) {
          password_ =
            com.google.protobuf.StringValue.newBuilder(password_).mergeFrom(value).buildPartial();
        } else {
          password_ = value;
        }
        onChanged();
      } else {
        passwordBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public Builder clearPassword() {
      if (passwordBuilder_ == null) {
        password_ = null;
        onChanged();
      } else {
        password_ = null;
        passwordBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public com.google.protobuf.StringValue.Builder getPasswordBuilder() {
      
      onChanged();
      return getPasswordFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getPasswordOrBuilder() {
      if (passwordBuilder_ != null) {
        return passwordBuilder_.getMessageOrBuilder();
      } else {
        return password_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : password_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue password = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getPasswordFieldBuilder() {
      if (passwordBuilder_ == null) {
        passwordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getPassword(),
                getParentForChildren(),
                isClean());
        password_ = null;
      }
      return passwordBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:user.CreateUserRequest)
  }

  // @@protoc_insertion_point(class_scope:user.CreateUserRequest)
  private static final com.test.grpc.CreateUserRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.grpc.CreateUserRequest();
  }

  public static com.test.grpc.CreateUserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateUserRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateUserRequest>() {
    public CreateUserRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateUserRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateUserRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateUserRequest> getParserForType() {
    return PARSER;
  }

  public com.test.grpc.CreateUserRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

