// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpc;

public interface PaymentMethodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.PaymentMethod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue creditCardNumber = 1;</code>
   */
  boolean hasCreditCardNumber();
  /**
   * <code>.google.protobuf.StringValue creditCardNumber = 1;</code>
   */
  com.google.protobuf.StringValue getCreditCardNumber();
  /**
   * <code>.google.protobuf.StringValue creditCardNumber = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getCreditCardNumberOrBuilder();

  /**
   * <code>.google.protobuf.StringValue creditCardType = 2;</code>
   */
  boolean hasCreditCardType();
  /**
   * <code>.google.protobuf.StringValue creditCardType = 2;</code>
   */
  com.google.protobuf.StringValue getCreditCardType();
  /**
   * <code>.google.protobuf.StringValue creditCardType = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getCreditCardTypeOrBuilder();
}
