// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpc;

public interface RemovePaymentMethodRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.RemovePaymentMethodRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userPid = 1;</code>
   */
  java.lang.String getUserPid();
  /**
   * <code>string userPid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserPidBytes();

  /**
   * <code>string creditCardNumber = 2;</code>
   */
  java.lang.String getCreditCardNumber();
  /**
   * <code>string creditCardNumber = 2;</code>
   */
  com.google.protobuf.ByteString
      getCreditCardNumberBytes();
}
