// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpc;

/**
 * Protobuf type {@code user.RemovePaymentMethodRequest}
 */
public  final class RemovePaymentMethodRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.RemovePaymentMethodRequest)
    RemovePaymentMethodRequestOrBuilder {
  // Use RemovePaymentMethodRequest.newBuilder() to construct.
  private RemovePaymentMethodRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemovePaymentMethodRequest() {
    userPid_ = "";
    creditCardNumber_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RemovePaymentMethodRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userPid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            creditCardNumber_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.test.grpc.User.internal_static_user_RemovePaymentMethodRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.test.grpc.User.internal_static_user_RemovePaymentMethodRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.test.grpc.RemovePaymentMethodRequest.class, com.test.grpc.RemovePaymentMethodRequest.Builder.class);
  }

  public static final int USERPID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userPid_;
  /**
   * <code>string userPid = 1;</code>
   */
  public java.lang.String getUserPid() {
    java.lang.Object ref = userPid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userPid_ = s;
      return s;
    }
  }
  /**
   * <code>string userPid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUserPidBytes() {
    java.lang.Object ref = userPid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userPid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREDITCARDNUMBER_FIELD_NUMBER = 2;
  private volatile java.lang.Object creditCardNumber_;
  /**
   * <code>string creditCardNumber = 2;</code>
   */
  public java.lang.String getCreditCardNumber() {
    java.lang.Object ref = creditCardNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creditCardNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string creditCardNumber = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCreditCardNumberBytes() {
    java.lang.Object ref = creditCardNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creditCardNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserPidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userPid_);
    }
    if (!getCreditCardNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, creditCardNumber_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserPidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userPid_);
    }
    if (!getCreditCardNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, creditCardNumber_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.test.grpc.RemovePaymentMethodRequest)) {
      return super.equals(obj);
    }
    com.test.grpc.RemovePaymentMethodRequest other = (com.test.grpc.RemovePaymentMethodRequest) obj;

    boolean result = true;
    result = result && getUserPid()
        .equals(other.getUserPid());
    result = result && getCreditCardNumber()
        .equals(other.getCreditCardNumber());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERPID_FIELD_NUMBER;
    hash = (53 * hash) + getUserPid().hashCode();
    hash = (37 * hash) + CREDITCARDNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCreditCardNumber().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.test.grpc.RemovePaymentMethodRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.test.grpc.RemovePaymentMethodRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.RemovePaymentMethodRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.RemovePaymentMethodRequest)
      com.test.grpc.RemovePaymentMethodRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.test.grpc.User.internal_static_user_RemovePaymentMethodRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.test.grpc.User.internal_static_user_RemovePaymentMethodRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.test.grpc.RemovePaymentMethodRequest.class, com.test.grpc.RemovePaymentMethodRequest.Builder.class);
    }

    // Construct using com.test.grpc.RemovePaymentMethodRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      userPid_ = "";

      creditCardNumber_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.test.grpc.User.internal_static_user_RemovePaymentMethodRequest_descriptor;
    }

    public com.test.grpc.RemovePaymentMethodRequest getDefaultInstanceForType() {
      return com.test.grpc.RemovePaymentMethodRequest.getDefaultInstance();
    }

    public com.test.grpc.RemovePaymentMethodRequest build() {
      com.test.grpc.RemovePaymentMethodRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.test.grpc.RemovePaymentMethodRequest buildPartial() {
      com.test.grpc.RemovePaymentMethodRequest result = new com.test.grpc.RemovePaymentMethodRequest(this);
      result.userPid_ = userPid_;
      result.creditCardNumber_ = creditCardNumber_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.test.grpc.RemovePaymentMethodRequest) {
        return mergeFrom((com.test.grpc.RemovePaymentMethodRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.test.grpc.RemovePaymentMethodRequest other) {
      if (other == com.test.grpc.RemovePaymentMethodRequest.getDefaultInstance()) return this;
      if (!other.getUserPid().isEmpty()) {
        userPid_ = other.userPid_;
        onChanged();
      }
      if (!other.getCreditCardNumber().isEmpty()) {
        creditCardNumber_ = other.creditCardNumber_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.test.grpc.RemovePaymentMethodRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.test.grpc.RemovePaymentMethodRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userPid_ = "";
    /**
     * <code>string userPid = 1;</code>
     */
    public java.lang.String getUserPid() {
      java.lang.Object ref = userPid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userPid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserPidBytes() {
      java.lang.Object ref = userPid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userPid = 1;</code>
     */
    public Builder setUserPid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userPid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userPid = 1;</code>
     */
    public Builder clearUserPid() {
      
      userPid_ = getDefaultInstance().getUserPid();
      onChanged();
      return this;
    }
    /**
     * <code>string userPid = 1;</code>
     */
    public Builder setUserPidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userPid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object creditCardNumber_ = "";
    /**
     * <code>string creditCardNumber = 2;</code>
     */
    public java.lang.String getCreditCardNumber() {
      java.lang.Object ref = creditCardNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creditCardNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string creditCardNumber = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreditCardNumberBytes() {
      java.lang.Object ref = creditCardNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creditCardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string creditCardNumber = 2;</code>
     */
    public Builder setCreditCardNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creditCardNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string creditCardNumber = 2;</code>
     */
    public Builder clearCreditCardNumber() {
      
      creditCardNumber_ = getDefaultInstance().getCreditCardNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string creditCardNumber = 2;</code>
     */
    public Builder setCreditCardNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creditCardNumber_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:user.RemovePaymentMethodRequest)
  }

  // @@protoc_insertion_point(class_scope:user.RemovePaymentMethodRequest)
  private static final com.test.grpc.RemovePaymentMethodRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.test.grpc.RemovePaymentMethodRequest();
  }

  public static com.test.grpc.RemovePaymentMethodRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemovePaymentMethodRequest>
      PARSER = new com.google.protobuf.AbstractParser<RemovePaymentMethodRequest>() {
    public RemovePaymentMethodRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemovePaymentMethodRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RemovePaymentMethodRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemovePaymentMethodRequest> getParserForType() {
    return PARSER;
  }

  public com.test.grpc.RemovePaymentMethodRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

