// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpc;

public interface StringsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.StringsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string request = 1;</code>
   */
  java.util.List<java.lang.String>
      getRequestList();
  /**
   * <code>repeated string request = 1;</code>
   */
  int getRequestCount();
  /**
   * <code>repeated string request = 1;</code>
   */
  java.lang.String getRequest(int index);
  /**
   * <code>repeated string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes(int index);
}
