// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpc;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 1;</code>
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>string fullName = 2;</code>
   */
  java.lang.String getFullName();
  /**
   * <code>string fullName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  boolean hasAddress();
  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  com.test.grpc.ShippingAddress getAddress();
  /**
   * <code>.user.ShippingAddress address = 3;</code>
   */
  com.test.grpc.ShippingAddressOrBuilder getAddressOrBuilder();

  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 5;</code>
   */
  java.util.List<com.test.grpc.PaymentMethod> 
      getPaymentMethodsList();
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 5;</code>
   */
  com.test.grpc.PaymentMethod getPaymentMethods(int index);
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 5;</code>
   */
  int getPaymentMethodsCount();
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 5;</code>
   */
  java.util.List<? extends com.test.grpc.PaymentMethodOrBuilder> 
      getPaymentMethodsOrBuilderList();
  /**
   * <code>repeated .user.PaymentMethod paymentMethods = 5;</code>
   */
  com.test.grpc.PaymentMethodOrBuilder getPaymentMethodsOrBuilder(
      int index);
}
