// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplier/supplier.proto

package com.test.grpc.supplier;

public interface SupplierUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:supplier.SupplierUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   */
  String getPid();
  /**
   * <code>string pid = 1;</code>
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>.supplier.Contact contact = 2;</code>
   */
  boolean hasContact();
  /**
   * <code>.supplier.Contact contact = 2;</code>
   */
  Contact getContact();
  /**
   * <code>.supplier.Contact contact = 2;</code>
   */
  ContactOrBuilder getContactOrBuilder();

  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();
}
