// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplier/supplier.proto

package com.test.grpc.supplier;

/**
 * Protobuf type {@code supplier.SuppliersResponse}
 */
public  final class SuppliersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:supplier.SuppliersResponse)
    SuppliersResponseOrBuilder {
  // Use SuppliersResponse.newBuilder() to construct.
  private SuppliersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SuppliersResponse() {
    suppliers_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SuppliersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              suppliers_ = new java.util.ArrayList<SupplierResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            suppliers_.add(
                input.readMessage(SupplierResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        suppliers_ = java.util.Collections.unmodifiableList(suppliers_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Supplier.internal_static_supplier_SuppliersResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Supplier.internal_static_supplier_SuppliersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SuppliersResponse.class, Builder.class);
  }

  public static final int SUPPLIERS_FIELD_NUMBER = 1;
  private java.util.List<SupplierResponse> suppliers_;
  /**
   * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
   */
  public java.util.List<SupplierResponse> getSuppliersList() {
    return suppliers_;
  }
  /**
   * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
   */
  public java.util.List<? extends SupplierResponseOrBuilder>
      getSuppliersOrBuilderList() {
    return suppliers_;
  }
  /**
   * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
   */
  public int getSuppliersCount() {
    return suppliers_.size();
  }
  /**
   * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
   */
  public SupplierResponse getSuppliers(int index) {
    return suppliers_.get(index);
  }
  /**
   * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
   */
  public SupplierResponseOrBuilder getSuppliersOrBuilder(
      int index) {
    return suppliers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < suppliers_.size(); i++) {
      output.writeMessage(1, suppliers_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < suppliers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, suppliers_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SuppliersResponse)) {
      return super.equals(obj);
    }
    SuppliersResponse other = (SuppliersResponse) obj;

    boolean result = true;
    result = result && getSuppliersList()
        .equals(other.getSuppliersList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSuppliersCount() > 0) {
      hash = (37 * hash) + SUPPLIERS_FIELD_NUMBER;
      hash = (53 * hash) + getSuppliersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SuppliersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SuppliersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SuppliersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SuppliersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SuppliersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SuppliersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SuppliersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SuppliersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SuppliersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SuppliersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SuppliersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SuppliersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SuppliersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code supplier.SuppliersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:supplier.SuppliersResponse)
      SuppliersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Supplier.internal_static_supplier_SuppliersResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Supplier.internal_static_supplier_SuppliersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SuppliersResponse.class, Builder.class);
    }

    // Construct using com.test.grpc.supplier.SuppliersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSuppliersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (suppliersBuilder_ == null) {
        suppliers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        suppliersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Supplier.internal_static_supplier_SuppliersResponse_descriptor;
    }

    public SuppliersResponse getDefaultInstanceForType() {
      return SuppliersResponse.getDefaultInstance();
    }

    public SuppliersResponse build() {
      SuppliersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public SuppliersResponse buildPartial() {
      SuppliersResponse result = new SuppliersResponse(this);
      int from_bitField0_ = bitField0_;
      if (suppliersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          suppliers_ = java.util.Collections.unmodifiableList(suppliers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.suppliers_ = suppliers_;
      } else {
        result.suppliers_ = suppliersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SuppliersResponse) {
        return mergeFrom((SuppliersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SuppliersResponse other) {
      if (other == SuppliersResponse.getDefaultInstance()) return this;
      if (suppliersBuilder_ == null) {
        if (!other.suppliers_.isEmpty()) {
          if (suppliers_.isEmpty()) {
            suppliers_ = other.suppliers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSuppliersIsMutable();
            suppliers_.addAll(other.suppliers_);
          }
          onChanged();
        }
      } else {
        if (!other.suppliers_.isEmpty()) {
          if (suppliersBuilder_.isEmpty()) {
            suppliersBuilder_.dispose();
            suppliersBuilder_ = null;
            suppliers_ = other.suppliers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            suppliersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSuppliersFieldBuilder() : null;
          } else {
            suppliersBuilder_.addAllMessages(other.suppliers_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SuppliersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SuppliersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<SupplierResponse> suppliers_ =
      java.util.Collections.emptyList();
    private void ensureSuppliersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        suppliers_ = new java.util.ArrayList<SupplierResponse>(suppliers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        SupplierResponse, SupplierResponse.Builder, SupplierResponseOrBuilder> suppliersBuilder_;

    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public java.util.List<SupplierResponse> getSuppliersList() {
      if (suppliersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(suppliers_);
      } else {
        return suppliersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public int getSuppliersCount() {
      if (suppliersBuilder_ == null) {
        return suppliers_.size();
      } else {
        return suppliersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public SupplierResponse getSuppliers(int index) {
      if (suppliersBuilder_ == null) {
        return suppliers_.get(index);
      } else {
        return suppliersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder setSuppliers(
        int index, SupplierResponse value) {
      if (suppliersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuppliersIsMutable();
        suppliers_.set(index, value);
        onChanged();
      } else {
        suppliersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder setSuppliers(
        int index, SupplierResponse.Builder builderForValue) {
      if (suppliersBuilder_ == null) {
        ensureSuppliersIsMutable();
        suppliers_.set(index, builderForValue.build());
        onChanged();
      } else {
        suppliersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder addSuppliers(SupplierResponse value) {
      if (suppliersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuppliersIsMutable();
        suppliers_.add(value);
        onChanged();
      } else {
        suppliersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder addSuppliers(
        int index, SupplierResponse value) {
      if (suppliersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSuppliersIsMutable();
        suppliers_.add(index, value);
        onChanged();
      } else {
        suppliersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder addSuppliers(
        SupplierResponse.Builder builderForValue) {
      if (suppliersBuilder_ == null) {
        ensureSuppliersIsMutable();
        suppliers_.add(builderForValue.build());
        onChanged();
      } else {
        suppliersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder addSuppliers(
        int index, SupplierResponse.Builder builderForValue) {
      if (suppliersBuilder_ == null) {
        ensureSuppliersIsMutable();
        suppliers_.add(index, builderForValue.build());
        onChanged();
      } else {
        suppliersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder addAllSuppliers(
        Iterable<? extends SupplierResponse> values) {
      if (suppliersBuilder_ == null) {
        ensureSuppliersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, suppliers_);
        onChanged();
      } else {
        suppliersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder clearSuppliers() {
      if (suppliersBuilder_ == null) {
        suppliers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        suppliersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public Builder removeSuppliers(int index) {
      if (suppliersBuilder_ == null) {
        ensureSuppliersIsMutable();
        suppliers_.remove(index);
        onChanged();
      } else {
        suppliersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public SupplierResponse.Builder getSuppliersBuilder(
        int index) {
      return getSuppliersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public SupplierResponseOrBuilder getSuppliersOrBuilder(
        int index) {
      if (suppliersBuilder_ == null) {
        return suppliers_.get(index);  } else {
        return suppliersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public java.util.List<? extends SupplierResponseOrBuilder>
         getSuppliersOrBuilderList() {
      if (suppliersBuilder_ != null) {
        return suppliersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(suppliers_);
      }
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public SupplierResponse.Builder addSuppliersBuilder() {
      return getSuppliersFieldBuilder().addBuilder(
          SupplierResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public SupplierResponse.Builder addSuppliersBuilder(
        int index) {
      return getSuppliersFieldBuilder().addBuilder(
          index, SupplierResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .supplier.SupplierResponse suppliers = 1;</code>
     */
    public java.util.List<SupplierResponse.Builder>
         getSuppliersBuilderList() {
      return getSuppliersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        SupplierResponse, SupplierResponse.Builder, SupplierResponseOrBuilder>
        getSuppliersFieldBuilder() {
      if (suppliersBuilder_ == null) {
        suppliersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            SupplierResponse, SupplierResponse.Builder, SupplierResponseOrBuilder>(
                suppliers_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        suppliers_ = null;
      }
      return suppliersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:supplier.SuppliersResponse)
  }

  // @@protoc_insertion_point(class_scope:supplier.SuppliersResponse)
  private static final SuppliersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SuppliersResponse();
  }

  public static SuppliersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SuppliersResponse>
      PARSER = new com.google.protobuf.AbstractParser<SuppliersResponse>() {
    public SuppliersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SuppliersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SuppliersResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SuppliersResponse> getParserForType() {
    return PARSER;
  }

  public SuppliersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

